import type { TrainingScenario } from "./training-scenarios.types";

export const TRAINING_SCENARIOS: TrainingScenario[] = [
  {
    id: "broker-cold-driver-easy",
    title: "Cold broker — driver (easy)",
    description:
      "First-touch broker who wants outcomes fast. You earn the next sentence with brevity and proof hooks.",
    goal: "Book a short demo or calendar slot without sounding desperate.",
    type: "BROKER",
    difficulty: "EASY",
    personality: "DRIVER",
    livePersona: "driver_broker",
    opening_line: "You’ve got my ear for ninety seconds — why should this matter to my desk today?",
    objections: [
      "That’s marketing — what metric moves in week one?",
      "Everyone says pipeline. Show me one live path I can verify.",
      "Still fluffy — bottom line or I’m gone.",
    ],
    success_condition: "broker_demo_booked",
  },
  {
    id: "broker-follow-amiable-med",
    title: "Follow-up — amiable broker",
    description:
      "Relationship-first broker needs safety and clarity. Guide with questions; avoid hard pressure.",
    goal: "Get agreement on a low-friction next step (short call or one-pager).",
    type: "BROKER",
    difficulty: "MEDIUM",
    personality: "AMIABLE",
    livePersona: "amiable_client",
    opening_line:
      "Hey — thanks for circling back. I’m open, but I need this to feel collaborative. What are we actually fixing?",
    objections: [
      "I’m worried we’ll add another tool nobody adopts.",
      "Can we keep this gentle — no hard closer stuff?",
      "I need to trust the handoff before I involve my team.",
    ],
    success_condition: "broker_demo_booked",
  },
  {
    id: "broker-skeptical-hard",
    title: "Burned broker — skeptical (hard)",
    description: "Broker has been sold empty promises. Proof-first; respect skepticism.",
    goal: "Earn a demo by showing observable behavior, not claims.",
    type: "BROKER",
    difficulty: "HARD",
    personality: "ANALYTICAL",
    livePersona: "skeptical_broker",
    opening_line: "Let me guess — another platform that ‘guarantees’ leads? Convince me without slogans.",
    objections: [
      "What integrates into my CRM today — not ‘roadmap’.",
      "I’ve seen three vendors with the same deck. What’s different in production?",
      "Unless you can show a live handoff, we’re done.",
    ],
    success_condition: "broker_demo_booked",
  },
  {
    id: "broker-aggressive-extreme",
    title: "Floor broker — extreme pressure",
    description: "Hostile time-boxed buyer. Control the frame with questions and time anchors.",
    goal: "Survive pressure and still land a concrete calendar ask.",
    type: "BROKER",
    difficulty: "EXTREME",
    personality: "DRIVER",
    livePersona: "aggressive_broker",
    opening_line: "Thirty seconds — why shouldn’t I hang up and block your number?",
    objections: [
      "You’re rambling — headline value only.",
      "Proof or fiction — pick one.",
      "This is the same pitch as everyone else. Last chance.",
    ],
    success_condition: "broker_demo_booked",
  },
  {
    id: "investor-analytical-easy",
    title: "Angel pass — analytical (easy)",
    description: "Investor wants mechanism and ranges. Teach briefly, then bridge to fit.",
    goal: "Secure a diligence or intro meeting with a clear agenda.",
    type: "INVESTOR",
    difficulty: "EASY",
    personality: "ANALYTICAL",
    livePersona: "analytical_investor",
    opening_line: "Walk me through unit economics at a high level — assumptions on paper are fine.",
    objections: [
      "Your payback sounds directional — what sensitivity breaks the model?",
      "Define the cohort you measure retention on.",
      "How do you reconcile growth claims to cash receipts?",
    ],
    success_condition: "investor_meeting_secured",
  },
  {
    id: "investor-dominant-med",
    title: "GP screen — dominant investor",
    description: "Capital allocator controls pace. Be concise; offer control illusion.",
    goal: "Lock a short meeting or partner intro — no feature tour.",
    type: "INVESTOR",
    difficulty: "MEDIUM",
    personality: "DRIVER",
    livePersona: "dominant_investor",
    opening_line: "Headline only — why does this deserve partner time this quarter?",
    objections: [
      "Still soft — where’s defensibility vs public comps?",
      "Too much story — give me one milestone you obsess over.",
      "Unless there’s traction I can diligence, we’re not scheduling.",
    ],
    success_condition: "investor_meeting_secured",
  },
  {
    id: "investor-expressive-hard",
    title: "Vision LP — expressive",
    description: "Buyer moves on narrative and upside. Anchor excitement to one concrete milestone.",
    goal: "Secure a next meeting tied to a story they can repeat internally.",
    type: "INVESTOR",
    difficulty: "HARD",
    personality: "EXPRESSIVE",
    livePersona: "expressive_user",
    opening_line:
      "Paint the picture — why should my team feel excited about this versus every other marketplace pitch?",
    objections: [
      "The vision’s thin — where’s the transformation moment?",
      "I need a hero outcome I can sell upstairs.",
      "Inspire me or stop — I’m not here for spreadsheets alone.",
    ],
    success_condition: "investor_meeting_secured",
  },
  {
    id: "investor-analytical-extreme",
    title: "IC memo — analytical extreme",
    description: "Institutional-style scrutiny. Precision, ranges, and audit mindset.",
    goal: "Earn a second meeting by surviving metric cross-exam.",
    type: "INVESTOR",
    difficulty: "EXTREME",
    personality: "ANALYTICAL",
    livePersona: "analytical_investor",
    opening_line:
      "Assume I’m writing an IC memo tonight — give me the falsifiable claims and what breaks them.",
    objections: [
      "Hand-wavy — reconcile ARR to bank statements.",
      "Which metric would make you kill the deal if it moved 10%?",
      "Still no audit path — we’re not advancing.",
    ],
    success_condition: "investor_meeting_secured",
  },
];
