/** Stable identifiers for audits, metrics, and explainability joins. */
export const AUTOPILOT_POLICY_RULE_IDS = {
  GLOBAL_PAUSE_ALL: "GLOBAL_PAUSE_ALL",
  DOMAIN_KILL_SWITCH_OFF: "DOMAIN_KILL_SWITCH_OFF",
  DOMAIN_KILL_SWITCH_LIMITED_NOT_ALLOWED: "DOMAIN_KILL_SWITCH_LIMITED_NOT_ALLOWED",
  MODE_OFF: "MODE_OFF",
  MATRIX_UNKNOWN_DOMAIN: "MATRIX_UNKNOWN_DOMAIN",
  MODE_DOES_NOT_ALLOW_AUTOMATIC: "MODE_DOES_NOT_ALLOW_AUTOMATIC",
  V1_BLOCKED_CATEGORY: "V1_BLOCKED_CATEGORY",
  HIGH_RISK_REQUIRES_APPROVAL: "HIGH_RISK_REQUIRES_APPROVAL",
  ASSIST_REQUIRES_APPROVAL: "ASSIST_REQUIRES_APPROVAL",
  SAFE_AUTOPILOT_LOW_RISK_AUTO: "SAFE_AUTOPILOT_LOW_RISK_AUTO",
  FULL_BOUNDED_LOW_RISK_AUTO: "FULL_BOUNDED_LOW_RISK_AUTO",
  FULL_APPROVAL_QUEUE: "FULL_APPROVAL_QUEUE",
  DISALLOWED_ACTION_FOR_DOMAIN: "DISALLOWED_ACTION_FOR_DOMAIN",
  /** Rare exemption: low-risk domain + whitelisted action while platform mode is approval-first. */
  FULL_APPROVAL_LOW_EXEMPT: "FULL_APPROVAL_LOW_EXEMPT",
  CONTEXT_FORCES_APPROVAL: "CONTEXT_FORCES_APPROVAL",
} as const;
