import type { ComplianceRule } from "@/lib/compliance/oaciq/representation-advertising/types";

/** Catalog — platform encoding of OACIQ advertising / representation duties (not legal advice). */
export const OACIQ_REPRESENTATION_ADVERTISING_RULES: ComplianceRule[] = [
  {
    id: "license_required_for_advertising",
    category: "representation",
    trigger: "user publishes or promotes real estate service",
    condition: "user does not hold valid brokerage license",
    violation: "illegal representation or advertising",
    prohibited_action: "publishing listings, ads, or brokerage services",
    risk_level: "high",
    source: "OACIQ",
  },
  {
    id: "mandatory_identity_in_advertising",
    category: "representation",
    trigger: "user creates advertisement or listing",
    condition: "missing broker name or title",
    violation: "non-compliant representation",
    required_action: "display broker name exactly as on license",
    risk_level: "high",
    source: "OACIQ",
  },
  {
    id: "mandatory_designation",
    category: "representation",
    trigger: "broker publishes service",
    condition: "missing designation (residential/commercial/etc)",
    violation: "misleading or incomplete representation",
    risk_level: "medium",
    source: "OACIQ",
  },
  {
    id: "respect_exclusive_contract",
    category: "solicitation",
    trigger: "user contacts property owner",
    condition: "property under exclusive brokerage contract",
    violation: "illegal solicitation",
    prohibited_action: "contacting or soliciting the client",
    risk_level: "high",
    source: "OACIQ",
  },
  {
    id: "no_referral_gifts",
    category: "promotion",
    trigger: "user offers incentive",
    condition: "gift offered in exchange for client referral",
    violation: "prohibited promotion practice",
    prohibited_action: "offering money or gifts for referrals",
    risk_level: "high",
    source: "OACIQ",
  },
  {
    id: "no_performance_guarantee",
    category: "representation",
    trigger: "user markets service",
    condition: "claims guaranteed sale or result",
    violation: "misleading representation",
    prohibited_action: "guaranteeing sale, price, or outcome",
    risk_level: "high",
    source: "OACIQ",
  },
  {
    id: "contract_required_before_ad",
    category: "advertising",
    trigger: "user publishes property",
    condition: "no signed brokerage contract",
    violation: "illegal advertising",
    prohibited_action: "posting listing before contract",
    risk_level: "high",
    source: "OACIQ",
  },
  {
    id: "coming_soon_prohibited",
    category: "advertising",
    trigger: "user posts teaser",
    condition: "contract not signed",
    violation: "misleading advertising",
    prohibited_action: "posting 'coming soon'",
    risk_level: "medium",
    source: "OACIQ",
  },
  {
    id: "no_selling_price_display",
    category: "advertising",
    trigger: "user advertises sold property",
    condition: "price is displayed",
    violation: "prohibited disclosure",
    prohibited_action: "displaying sold price",
    risk_level: "high",
    source: "OACIQ",
  },
  {
    id: "sold_label_required",
    category: "advertising",
    trigger: "transaction completed",
    condition: "no sold indication",
    violation: "incomplete information",
    required_action: "display SOLD notice",
    risk_level: "medium",
    source: "OACIQ",
  },
  {
    id: "supervision_required",
    category: "representation",
    trigger: "agency operates with brokers",
    condition: "no compliance oversight",
    violation: "regulatory breach",
    required_action: "implement compliance monitoring system",
    risk_level: "high",
    source: "OACIQ",
  },
];

export const DEFAULT_PUBLISH_RULE_SUBSET = [
  "license_required_for_advertising",
  "mandatory_identity_in_advertising",
  "contract_required_before_ad",
  "no_selling_price_display",
  "coming_soon_prohibited",
  "no_performance_guarantee",
  "mandatory_designation",
  "sold_label_required",
  "no_referral_gifts",
  "respect_exclusive_contract",
  "supervision_required",
] as const;
