import type { AiControlCenterSystems } from "@/modules/control-center/ai-control-center.types";

/** Minimal stub for unit tests — not exhaustive. */
export function minimalControlCenterSystems(overrides?: Partial<AiControlCenterSystems>): AiControlCenterSystems {
  const base: AiControlCenterSystems = {
    brain: {
      status: "healthy",
      summary: "brain ok",
      shadowObservationEnabled: true,
      influenceEnabled: false,
      primaryEnabled: false,
      fallbackRatePct: 12,
      warningCount: 0,
      comparisonRuns: 3,
      avgOverlapRate: 0.8,
      lastReportAt: null,
      topIssue: null,
      topRecommendation: null,
      detailsHref: null,
    },
    ads: {
      status: "healthy",
      summary: "ads ok",
      shadowMode: true,
      v8Rollout: true,
      influenceEnabled: false,
      primaryEnabled: false,
      comparisonRuns: 4,
      avgOverlapRate: 0.75,
      avgDivergenceRate: 0.1,
      pctRunsRisky: 10,
      anomalyNote: null,
      topRecommendation: null,
      detailsHref: null,
    },
    cro: {
      status: "healthy",
      summary: "cro ok",
      analysisEnabled: true,
      healthScore: 72,
      topBottleneck: null,
      dropoffSummary: "2 stages",
      recommendationCount: 1,
      readinessNote: null,
      warningSummary: null,
      detailsHref: null,
    },
    ranking: {
      status: "healthy",
      summary: "rank ok",
      totalScore: 80,
      maxScore: 100,
      recommendation: "expand_rollout_cautiously",
      readinessGatesOk: 4,
      readinessGatesTotal: 5,
      rollbackAny: false,
      top5Overlap: 0.9,
      avgRankShift: 0.02,
      warningsCount: 0,
      detailsHref: null,
    },
    operator: {
      status: "healthy",
      summary: "op",
      executionPlanFlag: false,
      simulationFlag: false,
      conflictEngineFlag: false,
      priorityScoringFlag: false,
      planCount: null,
      conflictCount: null,
      topRecommendation: null,
      detailsHref: null,
    },
    platformCore: {
      status: "healthy",
      summary: "pc",
      priorityEnabled: false,
      dependenciesEnabled: false,
      schedulerEnabled: false,
      simulationEnabled: false,
      pendingDecisions: 0,
      blockedDecisions: 0,
      overdueSchedules: 0,
      blockedDependencyEdges: null,
      healthWarnings: [],
      detailsHref: null,
    },
    fusion: {
      status: "limited",
      summary: "fusion",
      orchestrationActive: false,
      influenceEnabled: false,
      primaryEnabled: false,
      agreementHint: null,
      conflictCount: null,
      recommendationCount: null,
      healthNote: null,
      topRecommendation: null,
      detailsHref: null,
    },
    growthLoop: {
      status: "healthy",
      summary: "gl",
      systemEnabled: false,
      executionEnabled: false,
      simulationEnabled: false,
      lastRunStatus: null,
      lastRunAt: null,
      actionsProposed: null,
      actionsExecuted: null,
      notes: null,
      detailsHref: null,
    },
    swarm: {
      status: "healthy",
      summary: "sw",
      enabled: false,
      negotiationEnabled: false,
      influenceEnabled: false,
      primaryEnabled: false,
      agentSlots: 0,
      conflictCount: null,
      humanReviewCount: null,
      topOpportunity: null,
      negotiationNote: null,
      detailsHref: null,
    },
  };
  return { ...base, ...overrides };
}
