import type { FormDefinition } from "../../form-definition.types";

const identityFields = (prefix: string, role: string, index: number) => {
  const base = `${prefix}.${role}${index}`;
  return [
    {
      fieldKey: `${base}.fullName`,
      label: `${role} ${index} — name`,
      fieldType: "text" as const,
      required: index === 1,
      sourcePaths: [
        role === "buyer"
          ? `deal.parties.buyers[${index - 1}].fullName`
          : `deal.parties.sellers[${index - 1}].fullName`,
      ],
      displayGroup: `identity_${role}_${index}`,
      validationRuleRefs: ["pp.identity.name"],
      notes: "Specimen-aligned identity block",
    },
    {
      fieldKey: `${base}.address`,
      label: `${role} ${index} — address`,
      fieldType: "textarea" as const,
      required: false,
      sourcePaths: [
        role === "buyer"
          ? `deal.parties.buyers[${index - 1}].address`
          : `deal.parties.sellers[${index - 1}].address`,
      ],
      displayGroup: `identity_${role}_${index}`,
      validationRuleRefs: [],
    },
    {
      fieldKey: `${base}.phone`,
      label: `${role} ${index} — phone`,
      fieldType: "text" as const,
      required: false,
      sourcePaths: [
        role === "buyer"
          ? `deal.parties.buyers[${index - 1}].phone`
          : `deal.parties.sellers[${index - 1}].phone`,
      ],
      displayGroup: `identity_${role}_${index}`,
      validationRuleRefs: [],
    },
    {
      fieldKey: `${base}.email`,
      label: `${role} ${index} — email`,
      fieldType: "text" as const,
      required: false,
      sourcePaths: [
        role === "buyer"
          ? `deal.parties.buyers[${index - 1}].email`
          : `deal.parties.sellers[${index - 1}].email`,
      ],
      displayGroup: `identity_${role}_${index}`,
      validationRuleRefs: [],
    },
  ];
};

export const ppDefinition: FormDefinition = {
  formKey: "PP",
  officialCode: "PP",
  title: "Promise to purchase (residential) — specimen mapping",
  mandatoryOrRecommended: "mandatory",
  versionLabel: "mapper-v1",
  principalOrRelated: "principal",
  baseWorkflow: "residential_sale",
  sections: [
    {
      sectionKey: "pp.p1",
      sectionLabel: "PP.1 Identification of parties",
      order: 1,
      description: "Buyers, sellers, representative relationship",
      fields: [
        ...identityFields("pp.p1", "buyer", 1),
        ...identityFields("pp.p1", "buyer", 2),
        ...identityFields("pp.p1", "buyer", 3),
        ...identityFields("pp.p1", "buyer", 4),
        ...identityFields("pp.p1", "seller", 1),
        ...identityFields("pp.p1", "seller", 2),
        ...identityFields("pp.p1", "seller", 3),
        ...identityFields("pp.p1", "seller", 4),
        {
          fieldKey: "pp.p1.representative.relationship",
          label: "Representative relationship",
          fieldType: "textarea",
          required: false,
          sourcePaths: ["deal.broker.representativeRelationship"],
          displayGroup: "representative",
          validationRuleRefs: [],
        },
        {
          fieldKey: "pp.p1.representative.agencyName",
          label: "Agency / brokerage",
          fieldType: "text",
          required: false,
          sourcePaths: ["deal.broker.agencyName"],
          displayGroup: "representative",
          validationRuleRefs: [],
        },
      ],
    },
    {
      sectionKey: "pp.p2",
      sectionLabel: "PP.2 Object of promise to purchase",
      order: 2,
      fields: [
        {
          fieldKey: "pp.p2.brokerReference",
          label: "Broker / agency reference",
          fieldType: "text",
          required: false,
          sourcePaths: ["deal.broker.licenseNumber", "deal.broker.agencyName"],
          displayGroup: "object",
          validationRuleRefs: [],
        },
        {
          fieldKey: "pp.p2.businessCorporation",
          label: "Business corporation / agency / own account details",
          fieldType: "textarea",
          required: false,
          sourcePaths: ["deal.broker.businessDetails"],
          displayGroup: "object",
          validationRuleRefs: [],
        },
      ],
    },
    {
      sectionKey: "pp.p3",
      sectionLabel: "PP.3 Summary description of immovable",
      order: 3,
      fields: [
        {
          fieldKey: "pp.p3.address",
          label: "Civic address",
          fieldType: "textarea",
          required: true,
          sourcePaths: ["deal.immovable.addressLine", "deal.immovable.city", "deal.immovable.postalCode"],
          displayGroup: "immovable",
          validationRuleRefs: ["pp.immovable.address"],
        },
        {
          fieldKey: "pp.p3.cadastral",
          label: "Cadastral description",
          fieldType: "textarea",
          required: false,
          sourcePaths: ["deal.immovable.cadastralDescription"],
          displayGroup: "immovable",
          validationRuleRefs: [],
        },
        {
          fieldKey: "pp.p3.dimensions",
          label: "Dimensions / area",
          fieldType: "textarea",
          required: false,
          sourcePaths: ["deal.immovable.lotSize", "deal.immovable.buildingArea"],
          displayGroup: "immovable",
          validationRuleRefs: [],
        },
        {
          fieldKey: "pp.p3.coownership",
          label: "Co-ownership (divided) options",
          fieldType: "textarea",
          required: false,
          sourcePaths: ["deal.coownership.unitNumber", "deal.coownership.condoFees"],
          displayGroup: "immovable",
          validationRuleRefs: [],
        },
        {
          fieldKey: "pp.p3.parkingStorage",
          label: "Parking / storage / common portions",
          fieldType: "textarea",
          required: false,
          sourcePaths: ["deal.immovable.parking", "deal.immovable.storage"],
          displayGroup: "immovable",
          validationRuleRefs: [],
        },
      ],
    },
    {
      sectionKey: "pp.p4",
      sectionLabel: "PP.4 Price and deposit",
      order: 4,
      fields: [
        {
          fieldKey: "pp.p4.purchasePrice",
          label: "Purchase price",
          fieldType: "currency",
          required: true,
          sourcePaths: ["deal.price.purchasePrice"],
          displayGroup: "price",
          validationRuleRefs: ["pp.price.positive"],
        },
        {
          fieldKey: "pp.p4.gstApplicable",
          label: "GST applicable",
          fieldType: "boolean",
          required: false,
          sourcePaths: ["deal.price.gstApplicable"],
          displayGroup: "tax",
          validationRuleRefs: [],
        },
        {
          fieldKey: "pp.p4.qstApplicable",
          label: "QST applicable",
          fieldType: "boolean",
          required: false,
          sourcePaths: ["deal.price.qstApplicable"],
          displayGroup: "tax",
          validationRuleRefs: [],
        },
        {
          fieldKey: "pp.p4.depositAmount",
          label: "Deposit amount",
          fieldType: "currency",
          required: false,
          sourcePaths: ["deal.deposit.amount"],
          displayGroup: "deposit",
          validationRuleRefs: ["pp.deposit.if_amount_then_details"],
        },
        {
          fieldKey: "pp.p4.depositTiming",
          label: "Deposit timing",
          fieldType: "text",
          required: false,
          sourcePaths: ["deal.deposit.timing"],
          displayGroup: "deposit",
          validationRuleRefs: [],
        },
        {
          fieldKey: "pp.p4.depositMethod",
          label: "Deposit payment method",
          fieldType: "text",
          required: false,
          sourcePaths: ["deal.deposit.method"],
          displayGroup: "deposit",
          validationRuleRefs: [],
        },
        {
          fieldKey: "pp.p4.trusteeName",
          label: "Trustee / trust account",
          fieldType: "text",
          required: false,
          sourcePaths: ["deal.deposit.trusteeName"],
          displayGroup: "deposit",
          validationRuleRefs: [],
        },
      ],
    },
    {
      sectionKey: "pp.p5",
      sectionLabel: "PP.5 Method of payment",
      order: 5,
      fields: [
        { fieldKey: "pp.p5.deposit", label: "Deposit", fieldType: "currency", required: false, sourcePaths: ["deal.deposit.amount"], displayGroup: "method", validationRuleRefs: ["pp.method.total_match"] },
        { fieldKey: "pp.p5.additionalSum", label: "Additional sum", fieldType: "currency", required: false, sourcePaths: ["deal.price.additionalSum"], displayGroup: "method", validationRuleRefs: ["pp.method.total_match"] },
        { fieldKey: "pp.p5.newLoan", label: "New loan", fieldType: "currency", required: false, sourcePaths: ["deal.financing.newLoanAmount"], displayGroup: "method", validationRuleRefs: ["pp.method.total_match"] },
        { fieldKey: "pp.p5.existingLoan", label: "Existing loan (assumption / balance)", fieldType: "currency", required: false, sourcePaths: ["deal.financing.existingLoanBalance"], displayGroup: "method", validationRuleRefs: ["pp.method.total_match"] },
        { fieldKey: "pp.p5.balance", label: "Balance", fieldType: "currency", required: false, sourcePaths: ["deal.price.balance"], displayGroup: "method", validationRuleRefs: ["pp.method.total_match"] },
        { fieldKey: "pp.p5.totalPrice", label: "Total price (cross-check)", fieldType: "currency", required: true, sourcePaths: ["deal.price.purchasePrice"], displayGroup: "method", validationRuleRefs: ["pp.method.total_match"] },
      ],
    },
    {
      sectionKey: "pp.p6",
      sectionLabel: "PP.6 New hypothecary loan",
      order: 6,
      fields: [
        { fieldKey: "pp.p6.amount", label: "Loan amount", fieldType: "currency", required: false, sourcePaths: ["deal.financing.newLoanAmount"], displayGroup: "loan", validationRuleRefs: [] },
        { fieldKey: "pp.p6.maxRate", label: "Maximum rate", fieldType: "text", required: false, sourcePaths: ["deal.financing.maxRate"], displayGroup: "loan", validationRuleRefs: [] },
        { fieldKey: "pp.p6.amortization", label: "Amortization", fieldType: "text", required: false, sourcePaths: ["deal.financing.amortizationYears"], displayGroup: "loan", validationRuleRefs: [] },
        { fieldKey: "pp.p6.term", label: "Term", fieldType: "text", required: false, sourcePaths: ["deal.financing.term"], displayGroup: "loan", validationRuleRefs: [] },
        { fieldKey: "pp.p6.exclusiveMortgageBrokerage", label: "Exclusive mortgage brokerage declaration", fieldType: "boolean", required: false, sourcePaths: ["deal.financing.exclusiveMortgageBrokerage"], displayGroup: "loan", validationRuleRefs: [] },
        { fieldKey: "pp.p6.lenderUndertakingDeadline", label: "Lender undertaking deadline", fieldType: "date", required: false, sourcePaths: ["deal.dates.lenderUndertakingDeadline"], displayGroup: "loan", validationRuleRefs: [] },
        { fieldKey: "pp.p6.absenceUndertakingFollowUp", label: "Absence of undertaking — follow-up eligibility", fieldType: "textarea", required: false, sourcePaths: ["deal.conditions.absenceUndertakingFollowUp"], displayGroup: "loan", validationRuleRefs: [] },
      ],
    },
    {
      sectionKey: "pp.p7",
      sectionLabel: "PP.7+ Conditions & downstream references",
      order: 7,
      fields: [
        { fieldKey: "pp.p7.inspection", label: "Inspection", fieldType: "textarea", required: false, sourcePaths: ["deal.conditions.inspection"], displayGroup: "conditions", validationRuleRefs: [] },
        { fieldKey: "pp.p7.documentReview", label: "Document review", fieldType: "textarea", required: false, sourcePaths: ["deal.conditions.documentReview"], displayGroup: "conditions", validationRuleRefs: [] },
        { fieldKey: "pp.p7.sellerObligations", label: "Seller obligations", fieldType: "textarea", required: false, sourcePaths: ["deal.conditions.sellerObligations"], displayGroup: "conditions", validationRuleRefs: [] },
        { fieldKey: "pp.p7.deedOfSale", label: "Deed of sale", fieldType: "textarea", required: false, sourcePaths: ["deal.dates.deedOfSale"], displayGroup: "conditions", validationRuleRefs: [] },
        { fieldKey: "pp.p7.occupancy", label: "Occupancy", fieldType: "textarea", required: false, sourcePaths: ["deal.dates.occupancy"], displayGroup: "conditions", validationRuleRefs: [] },
        { fieldKey: "pp.p7.acceptanceTiming", label: "Acceptance timing", fieldType: "textarea", required: false, sourcePaths: ["deal.dates.acceptanceDeadline"], displayGroup: "conditions", validationRuleRefs: [] },
        { fieldKey: "pp.p7.annexRefs", label: "Annex references", fieldType: "textarea", required: false, sourcePaths: ["deal.documents.annexRefs"], displayGroup: "conditions", validationRuleRefs: [] },
        { fieldKey: "pp.p7.signaturesPlaceholder", label: "Signatures (placeholder)", fieldType: "signature_placeholder", required: false, sourcePaths: [], displayGroup: "signatures", validationRuleRefs: [], notes: "Preview only — not execution" },
      ],
    },
  ],
  dependencies: [
    { ruleId: "pp.requires_immovable", description: "Immovable address recommended before broker review", dependsOnFormKeys: [] },
  ],
  validationRules: [
    { ruleId: "pp.method.total_match", description: "Method of payment components should reconcile to purchase price" },
    { ruleId: "pp.deposit.if_amount_then_details", description: "If deposit amount, timing/method/trustee should be reviewed" },
    { ruleId: "pp.immovable.address", description: "Civic address required for mapping" },
    { ruleId: "pp.price.positive", description: "Purchase price must be positive when set" },
  ],
  previewOrder: [
    "pp.p1",
    "pp.p2",
    "pp.p3",
    "pp.p4",
    "pp.p5",
    "pp.p6",
    "pp.p7",
  ],
};
