/**
 * Short-Term Rental (BNHub) Booking Confirmation template.
 */
export const BOOKING_CONFIRMATION_TEMPLATE = `
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"/><title>Booking Confirmation</title></head>
<body style="font-family: system-ui, sans-serif; max-width: 700px; margin: 2rem auto; line-height: 1.5;">
  <h1>Booking Confirmation</h1>
  <p><strong>Booking ID:</strong> {{booking_id}}</p>
  <p>Generated on {{generated_date}}.</p>
  <h2>Property</h2>
  <p><strong>{{listing_title}}</strong></p>
  <p>{{property_address}}</p>
  <h2>Guest</h2>
  <p>{{guest_name}} ({{guest_email}})</p>
  <h2>Host</h2>
  <p>{{host_name}}{{#if host_email}} ({{host_email}}){{/if}}</p>
  <h2>Dates &amp; Amount</h2>
  <p><strong>Check-in:</strong> {{booking_start_date}}</p>
  <p><strong>Check-out:</strong> {{booking_end_date}}</p>
  <p><strong>Nights:</strong> {{nights}}</p>
  <p><strong>Subtotal:</strong> {{subtotal}}</p>
  {{#if cleaning_fee}}<p><strong>Cleaning fee:</strong> {{cleaning_fee}}</p>{{/if}}
  <p><strong>Service fee:</strong> {{service_fee}}</p>
  <p><strong>Total paid:</strong> {{total_amount}}</p>
  <p>This confirmation is generated by the LECIPM BNHub platform. House rules and check-in details are available in your booking dashboard.</p>
</body>
</html>
`.trim();
