/**
 * Offer to Purchase template.
 * Placeholders: property_address, buyer_name, buyer_email, seller_name, seller_email,
 * broker_name, broker_email, offer_price, closing_date, generated_date, cadastre_number.
 */
export const OFFER_TO_PURCHASE_TEMPLATE = `
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"/><title>Offer to Purchase</title></head>
<body style="font-family: system-ui, sans-serif; max-width: 700px; margin: 2rem auto; line-height: 1.5;">
  <h1>Offer to Purchase</h1>
  <p><strong>Property:</strong> {{property_address}}</p>
  {{#if cadastre_number}}<p><strong>Cadastre / Folio:</strong> {{cadastre_number}}</p>{{/if}}
  <p>This offer is made on {{generated_date}}.</p>
  <h2>Parties</h2>
  <p><strong>Buyer:</strong> {{buyer_name}} ({{buyer_email}})</p>
  <p><strong>Seller:</strong> {{seller_name}} ({{seller_email}})</p>
  {{#if broker_name}}<p><strong>Broker:</strong> {{broker_name}}{{#if broker_email}} ({{broker_email}}){{/if}}</p>{{/if}}
  <h2>Offer</h2>
  <p><strong>Purchase price:</strong> {{offer_price}}</p>
  {{#if closing_date}}<p><strong>Proposed closing date:</strong> {{closing_date}}</p>{{/if}}
  <p>This document is a draft generated by the LECIPM platform. It is not a legally binding offer until signed by all parties through the platform’s signing process.</p>
</body>
</html>
`.trim();
