/** Mirror of Prisma `PlatformRole`. Client-facing props must import from here instead of `@prisma/client`. */
export type PlatformRole =
  | "VISITOR"
  | "USER"
  | "CLIENT"
  | "TESTER"
  | "HOST"
  | "BROKER"
  | "MORTGAGE_EXPERT"
  | "DEVELOPER"
  | "ACCOUNTANT"
  | "ADMIN"
  | "PRIVACY_OFFICER"
  | "LEGAL_ADMIN"
  | "COMPLIANCE_STAFF"
  | "AGENCY_EXECUTIVE"
  | "UNREPRESENTED_BUYER"
  | "CONTENT_OPERATOR"
  | "LISTING_OPERATOR"
  | "OUTREACH_OPERATOR"
  | "OPERATOR"
  | "SUPPORT_AGENT"
  | "BUYER"
  | "SELLER_DIRECT"
  | "MORTGAGE_BROKER"
  | "INSURANCE_BROKER"
  | "INVESTOR";
