/**
 * Resolves DATABASE_URL from APP_ENV + *DATABASE_URL* sources.
 * Writes `.env.local` with DATABASE_URL only for APP_ENV=development (local dev), never for staging/production.
 * Does not read or write `.env.production` or any committed production-only files.
 */
const path = require("node:path");
const fs = require("node:fs");
const { config } = require("dotenv");

const appRoot = path.join(__dirname, "..");
const envPath = path.join(appRoot, ".env");
const localPath = path.join(appRoot, ".env.local");
if (fs.existsSync(envPath)) config({ path: envPath });
if (fs.existsSync(localPath)) {
  config({ path: localPath, override: true });
}

function isLocalishUrl(s) {
  return /127\.0\.0\.1|localhost|::1|^\[?::1\]?$/i.test(s);
}

function appEnvName() {
  const a = (process.env.APP_ENV || process.env.NODE_ENV || "development").toLowerCase();
  if (a === "prod" || a === "production") return "production";
  if (a === "stage" || a === "staging") return "staging";
  if (a === "dev" || a === "development") return "development";
  if (a === "test") return "development";
  return "development";
}

const mode = appEnvName();
let databaseUrl = "";

if (process.env.INVESTOR_DEMO_MODE === "true") {
  const s = (process.env.STAGING_DATABASE_URL || "").trim();
  if (!s) {
    throw new Error(
      "resolve-env-db: INVESTOR_DEMO_MODE requires STAGING_DATABASE_URL — never use PRODUCTION_DATABASE_URL for demo.",
    );
  }
  databaseUrl = s;
} else if (mode === "production") {
  const p = (process.env.PRODUCTION_DATABASE_URL || "").trim();
  if (!p) {
    throw new Error("resolve-env-db: set PRODUCTION_DATABASE_URL when APP_ENV=production.");
  }
  if (isLocalishUrl(p)) {
    throw new Error("resolve-env-db: production database URL must not be local.");
  }
  databaseUrl = p;
} else if (mode === "staging") {
  const s = (process.env.STAGING_DATABASE_URL || "").trim();
  if (!s) {
    throw new Error("resolve-env-db: set STAGING_DATABASE_URL when APP_ENV=staging.");
  }
  databaseUrl = s;
} else {
  const d = (process.env.DEV_DATABASE_URL || "").trim();
  if (d) {
    databaseUrl = d;
  } else {
    const cur = (process.env.DATABASE_URL || "").trim();
    if (cur) {
      databaseUrl = cur;
    } else if (process.env.ALLOW_LOCAL_DEV_DB === "0") {
      throw new Error(
        "resolve-env-db: set DEV_DATABASE_URL or DATABASE_URL, or unset ALLOW_LOCAL_DEV_DB=0 for local default.",
      );
    } else {
      throw new Error("resolve-env-db: set DEV_DATABASE_URL or DATABASE_URL for development.");
    }
  }
}

if (mode === "development") {
  const ANCHOR = "# <auto-generated by resolve-env-db — safe to delete>";
  const block = `${ANCHOR}\nDATABASE_URL=${JSON.stringify(String(databaseUrl))}\n\n`;
  let existing = fs.existsSync(localPath) ? fs.readFileSync(localPath, "utf8") : "";
  const esc = ANCHOR.replace(/[\\^$.*+?()[\]{}|]/g, "\\$&");
  const re = new RegExp(`${esc}[\\r\\n]+DATABASE_URL=.*[\\r\\n]*`, "m");
  const next = re.test(existing) ? existing.replace(re, block) : `${existing.trimEnd()}\n\n${block}`;
  fs.writeFileSync(localPath, next, "utf8");
  console.log("resolve-env-db: wrote DATABASE_URL to .env.local (development).");
} else {
  process.env.DATABASE_URL = databaseUrl;
  console.log(
    "resolve-env-db: resolved for non-dev mode — export DATABASE_URL in your host env (file not written).",
  );
}
