/**
 * Auto-extract: builds standalone Prisma entrypoints (one per domain) for multi-client
 * generation. Reads merged partials in prisma/ and prisma/model-domains.json when present.
 *
 * Prisma 7: datasource has no `url` here; URL comes from prisma.config.ts. Each generator
 * uses a distinct output to avoid clobbering a single @prisma/client.
 *
 * Usage (from apps/web):
 *   node scripts/split-prisma.js
 *   pnpm run prisma:extract
 */
const fs = require("node:fs");
const path = require("node:path");

const webRoot = path.join(__dirname, "..");
const prismaDir = path.join(webRoot, "prisma");
const inputFull = path.join(prismaDir, "schema.full.prisma");
const domainMapPath = path.join(prismaDir, "model-domains.json");

const PARTIALS = [
  "00-enums.prisma",
  "10-core.prisma",
  "20-marketplace.prisma",
  "30-compliance.prisma",
  "40-intelligence.prisma",
];

const rules = {
  core: [
    "User",
    "Account",
    "Session",
    "Role",
    "Permission",
    "Organization",
    "Team",
    "Auth",
  ],
  marketplace: [
    "Listing",
    "Property",
    "Booking",
    "Reservation",
    "Calendar",
    "Payment",
    "Transaction",
    "Invoice",
    "Stripe",
    "Host",
    "Guest",
    "BNHub",
    "Bnhub",
  ],
  compliance: [
    "Declaration",
    "Seller",
    "Audit",
    "Log",
    "Verification",
    "Identity",
    "Document",
    "Consent",
    "OACIQ",
    "Oaciq",
    "Disclosure",
    "Risk",
    "Complaint",
    "Register",
  ],
  analytics: [
    "Score",
    "Graph",
    "Embedding",
    "AI",
    "Ai",
    "Prediction",
    "Insight",
    "Metric",
    "Event",
    "Tracking",
    "Experiment",
    "Simulation",
    "Analyzer",
  ],
};

/** @type {["core", "marketplace", "compliance", "analytics"]} */
const DOMAIN_KEYS = ["core", "marketplace", "compliance", "analytics"];

function readMergedSource() {
  if (fs.existsSync(inputFull)) {
    return fs.readFileSync(inputFull, "utf-8");
  }
  return PARTIALS.map((f) => {
    const p = path.join(prismaDir, f);
    if (!fs.existsSync(p)) {
      throw new Error(`Missing ${f}; restore partials or add prisma/schema.full.prisma`);
    }
    return fs.readFileSync(p, "utf-8");
  }).join("\n\n");
}

/** Strip // @domain — not valid Prisma; remove before re-emitted */
function stripDomainComments(text) {
  return text
    .split("\n")
    .filter((l) => !/^\s*\/\/\s*@domain:\s*/.test(l))
    .filter((l) => !/^\s*\/\/\s*@domain:\s*enums/.test(l))
    .join("\n");
}

/**
 * @returns {{ type: "model" | "enum", name: string, text: string }[]}
 */
function extractTopLevelBlocks(text) {
  const t = stripDomainComments(text);
  const lines = t.split("\n");
  const blocks = [];
  let i = 0;
  while (i < lines.length) {
    const m = lines[i].match(/^(model|enum)\s+(\w+)\s*\{\s*$/);
    if (m) {
      const type = m[1];
      const name = m[2];
      let depth = 0;
      let j = i;
      for (; j < lines.length; j++) {
        for (const ch of lines[j]) {
          if (ch === "{") depth++;
          if (ch === "}") depth--;
        }
        if (j > i && depth === 0) {
          const body = lines.slice(i, j + 1).join("\n");
          blocks.push({ type, name, text: body });
          i = j + 1;
          break;
        }
      }
      if (j >= lines.length) {
        throw new Error(`Unclosed block at line ${i + 1} (${type} ${name})`);
      }
      continue;
    }
    i++;
  }
  return blocks;
}

let cachedMap = null;
function loadDomainMap() {
  if (cachedMap) return cachedMap;
  try {
    cachedMap = JSON.parse(fs.readFileSync(domainMapPath, "utf-8"));
  } catch {
    cachedMap = null;
  }
  return cachedMap;
}

function keywordClassifyModelName(name) {
  const n = name;
  const order = ["core", "marketplace", "compliance", "analytics"];
  for (const domain of order) {
    for (const keyword of rules[domain]) {
      if (n.includes(keyword)) {
        if (domain === "analytics" && /^(User|Session|Listing|Property|Booking)/.test(n)) {
          continue;
        }
        return domain;
      }
    }
  }
  return "analytics";
}

/**
 * @param {string} name
 * @param {"model"|"enum"} kind
 */
function resolveDomain(name, kind) {
  if (kind === "enum") {
    return "enums";
  }
  const map = loadDomainMap();
  if (map && map[name] && !String(map[name]).startsWith("enums:")) {
    const tag = map[name];
    if (tag === "intelligence" || tag === "analytics") return "analytics";
    if (["core", "marketplace", "compliance"].includes(tag)) return tag;
  }
  const k = keywordClassifyModelName(name);
  return k;
}

const header = (outName) => `// Autogenerated by scripts/split-prisma.js — do not edit by hand; fix cross-domain relations before relying on this client.
generator client {
  provider   = "prisma-client-js"
  output     = ${JSON.stringify(`../generated/${outName}`)}
  engineType = "binary"
}

datasource db {
  provider = "postgresql"
}
`;

function main() {
  const content = readMergedSource();
  const blocks = extractTopLevelBlocks(content);

  const domains = {
    core: [],
    marketplace: [],
    compliance: [],
    analytics: [],
    enums: [],
  };

  for (const b of blocks) {
    if (b.type === "enum") {
      domains.enums.push(b.text.trim());
      continue;
    }
    const d = resolveDomain(b.name, "model");
    const bucket = d === "enums" ? "core" : d;
    if (!domains[bucket]) {
      throw new Error(`Unknown bucket ${bucket} for model ${b.name}`);
    }
    domains[bucket].push(b.text.trim());
  }

  const enumText = domains.enums.length ? `${domains.enums.join("\n\n")}\n\n` : "";
  for (const key of DOMAIN_KEYS) {
    const outName = key;
    const outDir = path.join(prismaDir, outName);
    const filePath = path.join(outDir, "schema.prisma");
    const modelsPart = domains[key].length ? domains[key].join("\n\n") : "";
    const nModels = domains[key].length;
    const data = `${header(outName)}${enumText}${
      modelsPart ? modelsPart : "\n// (no models in this domain yet)\n"
    }`;
    fs.mkdirSync(outDir, { recursive: true });
    fs.writeFileSync(filePath, data, "utf-8");
    process.stdout.write(
      `✔ Wrote ${path.relative(webRoot, filePath)} (${nModels} models; enums repeated in all 4 for standalone validate)\n`,
    );
  }

  process.stdout.write(
    "\nNext: pnpm exec prisma generate --schema=./prisma/core/schema.prisma  (and marketplace, compliance, analytics as needed)\n" +
      "      Expect validation errors until cross-schema @relation fields are removed or replaced with scalar FKs (see docs / manual Step 5).\n",
  );
}

main();
