/** Consistent attribution line for investment surfaces (prints, sharing, footers). */
export function GeneratedByLecipm({ className = "" }: { className?: string }) {
  return (
    <p
      className={`text-center text-xs font-medium tracking-wide text-slate-500 sm:text-sm ${className}`.trim()}
      role="note"
    >
      Generated by <span className="font-semibold text-[#C9A646]">LECIPM</span>
    </p>
  );
}
