/**
 * Québec localités for investment / deal analyzer (mock benchmarks are provincial or metro-level).
 * Organized by administrative region — optgroups in UI. Names use common French forms.
 */

export type QuebecRegionGroup = { label: string; cities: readonly string[] };

export const QUEBEC_CITY_GROUPS: readonly QuebecRegionGroup[] = [
  {
    label: "Montréal (agglomération)",
    cities: [
      "Montréal",
      "Westmount",
      "Mont-Royal",
      "Hampstead",
      "Côte-Saint-Luc",
      "Montréal-Est",
      "Montréal-Ouest",
      "Dorval",
      "Pointe-Claire",
      "Kirkland",
      "Beaconsfield",
      "Baie-D'Urfé",
      "Sainte-Anne-de-Bellevue",
      "Senneville",
    ],
  },
  {
    label: "Laval",
    cities: ["Laval"],
  },
  {
    label: "Montérégie",
    cities: [
      "Longueuil",
      "Brossard",
      "Saint-Lambert",
      "Boucherville",
      "Varennes",
      "Verchères",
      "Contrecoeur",
      "Sorel-Tracy",
      "Saint-Jean-sur-Richelieu",
      "Chambly",
      "Carignan",
      "Granby",
      "Cowansville",
      "Bromont",
      "Farnham",
      "Bedford",
      "Saint-Hyacinthe",
      "Acton Vale",
      "Marieville",
      "Richelieu",
      "Saint-Césaire",
      "Candiac",
      "Delson",
      "La Prairie",
      "Saint-Constant",
      "Sainte-Catherine",
      "Châteauguay",
      "Mercier",
      "Sainte-Martine",
      "Beauharnois",
      "Salaberry-de-Valleyfield",
      "Huntingdon",
      "Hemmingford",
      "Saint-Urbain-Premier",
      "Noyan",
      "Saint-Philippe",
      "Léry",
      "Kahnawake",
    ],
  },
  {
    label: "Laurentides",
    cities: [
      "Saint-Jérôme",
      "Mirabel",
      "Blainville",
      "Boisbriand",
      "Rosemère",
      "Sainte-Thérèse",
      "Lorraine",
      "Deux-Montagnes",
      "Saint-Eustache",
      "Pointe-Calumet",
      "Oka",
      "Saint-Placide",
      "Hudson",
      "Saint-Lazare",
      "Vaudreuil-Dorion",
      "Les Cèdres",
      "Côteau-du-Lac",
      "Rigaud",
      "Sainte-Agathe-des-Monts",
      "Estérel",
      "Sainte-Adèle",
      "Prévost",
      "Saint-Sauveur",
      "Morin-Heights",
      "Val-David",
      "Val-Morin",
      "Mont-Tremblant",
      "Lac-Supérieur",
      "Labelle",
      "La Conception",
      "Brébeuf",
      "Arundel",
      "Montcalm",
      "Lac-des-Seize-Îles",
      "Sainte-Lucie-des-Laurentides",
      "Amherst",
      "Lac-des-Écorces",
      "Nominingue",
      "La Macaza",
      "Rivière-Rouge",
      "L'Ascension-de-Notre-Seigneur",
      "Mont-Laurier",
      "Lac-Simon",
      "Chénéville",
      "Duhamel",
      "Kiamika",
      "Ferme-Neuve",
    ],
  },
  {
    label: "Lanaudière",
    cities: [
      "Joliette",
      "Repentigny",
      "Charlemagne",
      "L'Assomption",
      "L'Épiphanie",
      "Saint-Sulpice",
      "Lavaltrie",
      "Lanoraie",
      "Berthierville",
      "Saint-Didace",
      "Saint-Gabriel-de-Brandon",
      "Saint-David",
      "Maskinongé",
      "Louiseville",
      "Saint-Barthélemy",
      "Rawdon",
      "Chertsey",
      "Notre-Dame-de-la-Merci",
      "Saint-Donat",
      "Saint-Côme",
      "Saint-Damien",
      "Sainte-Béatrix",
      "Saint-Jean-de-Matha",
      "Sainte-Mélanie",
      "Saint-Zénon",
      "Saint-Michel-des-Saints",
      "Saint-Jacques",
      "Saint-Liguori",
      "Entrelacs",
      "Saint-Alphonse-Rodriguez",
      "Sainte-Marcelline-de-Kildare",
      "Saint-Cléophas-de-Brandon",
      "Saint-Joseph-de-Maskinongé",
      "Saint-Paulin",
      "Saint-Alexis-des-Monts",
      "Saint-Boniface",
      "Saint-Élie-de-Caxton",
      "Saint-Jean-de-Matha",
      "Crabtree",
      "Saint-Pierre",
      "Saint-Thomas",
    ],
  },
  {
    label: "Capitale-Nationale",
    cities: [
      "Québec",
      "Lévis",
      "Saint-Augustin-de-Desmaures",
      "L'Ancienne-Lorette",
      "Saint-Foy",
      "Sainte-Foy",
      "Charlesbourg",
      "Beauport",
      "La Haute-Saint-Charles",
      "Loretteville",
      "Val-Bélair",
      "Cap-Rouge",
      "Sainte-Catherine-de-la-Jacques-Cartier",
      "Pont-Rouge",
      "Donnacona",
      "Portneuf",
      "Deschambault-Grondines",
      "Neuville",
      "Saint-Casimir",
      "Saint-Raymond",
      "Saint-Thuribe",
      "Saint-Gilbert",
      "Saint-Alban",
      "Saint-Ubalde",
      "Rivière-à-Pierre",
      "Lac-Beauport",
      "Stoneham-et-Tewkesbury",
      "Lac-Saint-Joseph",
      "Shannon",
      "Saint-Gabriel-de-Valcartier",
      "Sainte-Catherine-de-Hatley",
      "North Hatley",
      "Stanstead",
      "Coaticook",
      "Compton",
      "Martinville",
      "Saint-Malo",
      "Saint-Venant-de-Paquette",
      "East Hereford",
      "Dixville",
      "Ayer's Cliff",
    ],
  },
  {
    label: "Chaudière-Appalaches",
    cities: [
      "Lévis",
      "Saint-Joseph-de-Beauce",
      "Saint-Georges",
      "Plessisville",
      "Thetford Mines",
      "Disraeli",
      "East Broughton",
      "Adstock",
      "Sacré-Coeur-de-Jésus",
      "Saint-Ferdinand",
      "Saint-Sophie-d'Halifax",
      "Irlande",
      "Saint-Julien",
      "Saint-Joseph-de-Coleraine",
      "Saint-Adrien-d'Irlande",
      "Saint-Jacques-le-Majeur-de-Wolfestown",
      "Saint-Séverin",
      "Saint-Jacques-de-Leeds",
      "Kinnear's Mills",
      "Saint-Patrice-de-Beaurivage",
      "Saint-Gilles",
      "Saint-Agapit",
      "Saint-Jean-Chrysostome",
      "Sainte-Hénédine",
      "Saint-Benjamin",
      "Saints-Anges",
      "Saint-Bernard",
      "Saint-Nazaire-d'Acton",
      "Sainte-Agathe-de-Lotbinière",
      "Sainte-Sophie-d'Halifax",
      "Saint-Sylvestre",
      "Saint-Patrice-de-Sherrington",
      "Beauceville",
      "Saint-Frédéric",
      "Saint-Sébastien",
      "Saint-Martin",
      "Saint-Louis-de-Gonzague",
      "Saint-Côme–Linière",
      "Saint-Honoré-de-Shenley",
      "Tring-Jonction",
      "Saint-Joseph-de-Beauce",
      "Saint-Prosper",
      "Saint-Zacharie",
      "Saint-Luc-de-Bellechasse",
      "Saint-Magloire",
      "Sainte-Lucie-de-Beauregard",
      "Saint-Louis-de-Gonzague",
      "Saint-Cyprien",
      "Saint-Robert-Bellarmin",
      "Saint-Gédéon",
      "Saint-Hilaire-Dorset",
      "Saint-Adrien",
      "Sainte-Perpétue",
      "Témiscouata-sur-le-Lac",
    ],
  },
  {
    label: "Estrie",
    cities: [
      "Sherbrooke",
      "Magog",
      "Coaticook",
      "Compton",
      "East Angus",
      "Ascot Corner",
      "Westbury",
      "Hampden",
      "Marbleton",
      "Nantes",
      "Saint-Malo",
      "Chartierville",
      "Dixville",
      "Ayer's Cliff",
      "North Hatley",
      "Ogden",
      "Stanstead",
      "Stanstead-Est",
      "Beebe Plain",
      "Rock Forest",
      "Saint-Élie-d'Orford",
      "Orford",
      "Austin",
      "Bolton-Est",
      "Bolton-Ouest",
      "Bonsecours",
      "Brome",
      "Brookline",
      "Canton de Bedford",
      "Canton de Stanbridge",
      "Cleveland",
      "Cowansville",
      "Dunham",
      "East Farnham",
      "Farnham",
      "Frelighsburg",
      "Granby",
      "Hatley",
      "Lawrenceville",
      "Mansonville",
      "Notre-Dame-de-Stanbridge",
      "Pike River",
      "Roxton",
      "Roxton Pond",
      "Saint-Armand",
      "Saint-Étienne-de-Bolton",
      "Saint-Georges-de-Clarenceville",
      "Saint-Ignace-de-Stanbridge",
      "Saint-Joachim-de-Shefford",
      "Saint-Pierre-de-Broughton",
      "Sutton",
      "Warden",
      "Waterloo",
      "Wotton",
      "Bedford",
      "Bedford Township",
      "Valcourt",
      "Richmond",
      "Melbourne",
      "Ulverton",
      "Danville",
      "Kingsey Falls",
      "Chesterville",
      "Ham-Nord",
      "Tingwick",
      "Saint-Ferdinand",
      "Princeville",
      "Plessisville",
      "Laurierville",
      "Lyster",
      "Irlande",
    ],
  },
  {
    label: "Centre-du-Québec",
    cities: [
      "Drummondville",
      "Victoriaville",
      "Bécancour",
      "Nicolet",
      "Saint-Célestin",
      "Saint-Léonard-d'Aston",
      "Saint-Wenceslas",
      "Saint-Eugène",
      "Saint-Edmond",
      "Lemieux",
      "Saint-Pierre-les-Becquets",
      "Deschaillons-sur-Saint-Laurent",
      "Fortierville",
      "Parisville",
      "Sainte-Sophie-de-Lévrard",
      "Sainte-Françoise",
      "Saint-Ferdinand",
      "Laurierville",
      "Lourdes",
      "Notre-Dame-du-Bon-Conseil",
      "Saint-Christophe-d'Arthabaska",
      "Saint-Lucien",
      "Saint-Samuel",
      "Sainte-Séraphine",
      "Warwick",
      "Saint-Albert",
      "Saint-Norbert-d'Arthabaska",
      "Maddington",
      "Saint-Valère",
      "Tingwick",
      "Chesterville",
      "Kingsey Falls",
      "Danville",
      "Asbestos",
      "Saint-Luc-de-Vincennes",
      "Saint-Sévère",
      "Charette",
      "Saint-Boniface",
      "Saint-Étienne-des-Grès",
      "Yamachiche",
      "Saint-Mathieu-du-Parc",
      "Trois-Rives",
      "Grandes-Piles",
      "Hérouxville",
      "Saint-Tite",
      "Saint-Séverin",
      "Sainte-Thècle",
      "Saint-Adelphe",
      "Lac-aux-Sables",
      "Notre-Dame-de-Montauban",
      "Rivière-à-Pierre",
    ],
  },
  {
    label: "Mauricie",
    cities: [
      "Trois-Rivières",
      "Shawinigan",
      "La Tuque",
      "Louiseville",
      "Maskinongé",
      "Saint-Boniface",
      "Saint-Élie-de-Caxton",
      "Saint-Mathieu-du-Parc",
      "Saint-Paulin",
      "Saint-Alexis-des-Monts",
      "Aston-Jonction",
      "Saint-Wenceslas",
      "Saint-Sévère",
      "Charette",
      "Saint-Étienne-des-Grès",
      "Yamachiche",
      "Saint-Barnabé-Sud",
      "Saint-Luc-de-Vincennes",
      "Saint-Sévère",
      "Grandes-Piles",
      "Hérouxville",
      "Saint-Tite",
      "Saint-Séverin",
      "Sainte-Thècle",
      "Saint-Adelphe",
      "Lac-aux-Sables",
      "Notre-Dame-de-Montauban",
      "Rivière-à-Pierre",
      "Parent",
      "Rivière-à-la-Truite",
      "Lac-Bouchette",
      "Chambord",
      "Roberval",
      "Saint-André-du-Lac-Saint-Jean",
      "Saint-François-de-Sales",
      "Desbiens",
      "Hébertville",
      "Métabetchouan-Lac-à-la-Croix",
    ],
  },
  {
    label: "Saguenay–Lac-Saint-Jean",
    cities: [
      "Saguenay",
      "Alma",
      "Roberval",
      "Chambord",
      "Saint-André-du-Lac-Saint-Jean",
      "Saint-François-de-Sales",
      "Desbiens",
      "Hébertville",
      "Hébertville-Station",
      "Métabetchouan-Lac-à-la-Croix",
      "Labrecque",
      "Lamarche",
      "Saint-Prime",
      "Albanel",
      "Normandin",
      "Saint-Edmond-les-Plaines",
      "Péribonka",
      "Saint-Stanislas",
      "Saint-Thomas-Didyme",
      "Girardville",
      "Saint-Eugène-d'Argentenay",
      "Saint-Félicien",
      "La Doré",
      "Mashteuiatsh",
      "Pessamit",
      "Saint-Ambroise",
      "Saint-Charles-de-Bourget",
      "Saint-David-de-Falardeau",
      "Saint-Fulgence",
      "Saint-Honoré",
      "Saint-Ludger-de-Milot",
      "Saint-Nazaire",
      "Saint-Prime",
      "Shipshaw",
      "Laterrière",
      "Jonquière",
      "Chicoutimi",
      "La Baie",
      "Ferland-et-Boilleau",
      "L'Anse-Saint-Jean",
      "Petit-Saguenay",
      "Rivière-Éternité",
      "Lalemand",
      "Lamarche",
      "Labrecque",
    ],
  },
  {
    label: "Outaouais",
    cities: [
      "Gatineau",
      "Cantley",
      "Chelsea",
      "La Pêche",
      "Low",
      "Mayo",
      "Pontiac",
      "Val-des-Monts",
      "L'Ange-Gardien",
      "Notre-Dame-de-la-Salette",
      "Gracefield",
      "Bouchette",
      "Blue Sea",
      "Déléage",
      "Messines",
      "Maniwaki",
      "Montcerf-Lytle",
      "Aumond",
      "Barraute",
      "Belleterre",
      "Champneuf",
      "Kipawa",
      "Laforce",
      "Laniel",
      "Latulipe-et-Gaboury",
      "Laverlochère-Angliers",
      "Lebel-sur-Quévillon",
      "Lorrainville",
      "Moffet",
      "Nédélec",
      "Notre-Dame-du-Nord",
      "Rémigny",
      "Rivière-Héva",
      "Rollet",
      "Saint-Eugène-de-Grantham",
      "Saint-Édouard-de-Fabre",
      "Senneville",
      "Témiscaming",
      "Ville-Marie",
      "Béarn",
      "Guérin",
      "Kebaowek",
      "Malartic",
      "McWatters",
      "Obedjiwan",
      "Palmarolle",
      "Poularies",
      "Rapide-Danseur",
      "Rivière-Ojima",
      "Roquemaure",
      "Saint-Lambert",
      "Saint-Marc-de-Figuery",
      "Sainte-Germaine-Boulé",
      "Sainte-Hélène-de-Mancebourg",
      "Authier",
      "Authier-Nord",
      "Chazel",
      "Clermont",
      "Clerval",
      "Duparquet",
      "Dupuy",
      "Gallichan",
      "La Corne",
      "La Morandière-Rochebaucourt",
      "La Motte",
      "La Reine",
      "Landrienne",
      "Macamic",
      "Normétal",
      "Palmarolle",
      "Pikogan",
      "Plamondon",
      "Rapide-Danseur",
      "Rivière-Héva",
      "Rollet",
      "Roquemaure",
      "Saint-Dominique-du-Rosaire",
      "Saint-Eugène-de-Guigues",
      "Saint-Marc-de-Figuery",
      "Sainte-Germaine-Boulé",
      "Sainte-Hélène-de-Mancebourg",
      "Taschereau",
      "Trécesson",
      "Val-Saint-Gilles",
      "Villebois",
    ],
  },
  {
    label: "Abitibi-Témiscamingue",
    cities: [
      "Rouyn-Noranda",
      "Val-d'Or",
      "Amos",
      "La Sarre",
      "Malartic",
      "Senneterre",
      "Belcourt",
      "Champneuf",
      "Clermont",
      "La Morandière-Rochebaucourt",
      "La Motte",
      "Landrienne",
      "Macamic",
      "Normétal",
      "Palmarolle",
      "Pikogan",
      "Rapide-Danseur",
      "Rivière-Héva",
      "Roquemaure",
      "Saint-Marc-de-Figuery",
      "Sainte-Germaine-Boulé",
      "Taschereau",
      "Trécesson",
      "Villebois",
      "Authier",
      "Authier-Nord",
      "Chazel",
      "Clerval",
      "Duparquet",
      "Dupuy",
      "Gallichan",
      "La Corne",
      "La Reine",
      "Obedjiwan",
      "Poularies",
      "Rémigny",
      "Saint-Eugène-de-Guigues",
      "Saint-Dominique-du-Rosaire",
      "Val-Saint-Gilles",
      "Béarn",
      "Guérin",
      "Kebaowek",
      "McWatters",
      "Témiscaming",
      "Ville-Marie",
      "Laniel",
      "Kipawa",
      "Laforce",
      "Latulipe-et-Gaboury",
      "Notre-Dame-du-Nord",
      "Nédélec",
      "Belleterre",
      "Laverlochère-Angliers",
      "Lebel-sur-Quévillon",
    ],
  },
  {
    label: "Côte-Nord",
    cities: [
      "Baie-Comeau",
      "Sept-Îles",
      "Port-Cartier",
      "Forestville",
      "Longue-Pointe-de-Mingan",
      "Aguanish",
      "Baie-Johan-Beetz",
      "Baie-Trinité",
      "Bonaventure",
      "Chute-aux-Outardes",
      "Colombier",
      "Franquelin",
      "Godbout",
      "Les Bergeronnes",
      "Les Escoumins",
      "Pointe-aux-Outardes",
      "Pointe-Lebel",
      "Portneuf-sur-Mer",
      "Ragueneau",
      "Saint-Urbain",
      "Les Méchins",
      "Matane",
      "Saint-Ulric",
      "Saint-René-de-Matane",
      "Saint-Adelme",
      "Saint-Jérôme-de-Matane",
      "Saint-Léandre",
      "Saint-Zénon-du-Lac-Humqui",
      "Sainte-Paule",
      "Sainte-Irène",
      "Sainte-Flavie",
      "Sainte-Luce",
      "Sainte-Anne-des-Monts",
      "Cap-Chat",
      "Marsoui",
      "Mont-Albert",
      "Grande-Vallée",
      "Gaspé",
      "Percé",
      "Grande-Rivière",
      "Chandler",
      "Port-Daniel–Gascons",
      "Shigawake",
      "Hope Town",
      "Saint-Godefroi",
      "Saint-Maurice-de-l'Échouerie",
      "Cloridorme",
      "Petite-Vallée",
      "Rivière-au-Tonnerre",
      "Mingan",
      "Natashquan",
      "Aguanish",
      "Baie-Johan-Beetz",
    ],
  },
  {
    label: "Gaspésie–Îles-de-la-Madeleine",
    cities: [
      "Gaspé",
      "Percé",
      "Grande-Rivière",
      "Chandler",
      "Port-Daniel–Gascons",
      "Shigawake",
      "Hope Town",
      "Saint-Godefroi",
      "Saint-Maurice-de-l'Échouerie",
      "Cloridorme",
      "Petite-Vallée",
      "Grande-Vallée",
      "Mont-Albert",
      "Marsoui",
      "Cap-Chat",
      "Sainte-Anne-des-Monts",
      "Sainte-Luce",
      "Sainte-Flavie",
      "Sainte-Irène",
      "Sainte-Paule",
      "Saint-Zénon-du-Lac-Humqui",
      "Saint-Léandre",
      "Saint-Jérôme-de-Matane",
      "Saint-Adelme",
      "Saint-René-de-Matane",
      "Saint-Ulric",
      "Matane",
      "Les Méchins",
      "Cap-aux-Meules",
      "Fatima",
      "Grande-Entrée",
      "Grosse-Île",
      "Havre-aux-Maisons",
      "L'Étang-du-Nord",
      "Pointe-aux-Loups",
      "Havre-Aubert",
    ],
  },
  {
    label: "Bas-Saint-Laurent",
    cities: [
      "Rimouski",
      "Mont-Joli",
      "Amqui",
      "Matane",
      "Témiscouata-sur-le-Lac",
      "Dégelis",
      "Pohenegamook",
      "Saint-Antonin",
      "Saint-Jean-de-Dieu",
      "Saint-Juste-du-Lac",
      "Auclair",
      "Biencourt",
      "Esprit-Saint",
      "Lac-des-Aigles",
      "Lejeune",
      "Packington",
      "Rivière-Bleue",
      "Saint-Cyprien",
      "Saint-Jean-de-Cherbourg",
      "Saint-Médard",
      "Saint-Michel-du-Squatec",
      "Saint-Pierre-de-Lamy",
      "Sainte-Françoise",
      "Sainte-Rita",
      "Tête-à-la-Baleine",
      "Saint-Gabriel-Lalemant",
      "Les Escoumins",
      "Les Bergeronnes",
      "Forestville",
      "Longue-Pointe-de-Mingan",
      "Rivière-Saint-Jean",
      "Saint-Narcisse-de-Rimouski",
      "Lac-Huron",
      "Esprit-Saint",
      "La Rédemption",
      "Saint-Charles-Garnier",
      "Saint-Donat",
      "Saint-Gabriel-de-Rimouski",
      "Saint-Marcellin",
      "Saint-Médard",
      "Saint-Simon",
      "Saint-Valérien",
      "Sainte-Angèle-de-Mérici",
      "Sainte-Blandine",
      "Sainte-Flavie",
      "Sainte-Irène",
      "Sainte-Luce",
      "Sainte-Paule",
      "Albertville",
      "Causapscal",
      "Lac-Casault",
      "Lac-des-Eaux-Mortes",
      "Lac-Normand",
      "Saint-André-de-Restigouche",
      "Saint-Alexis-de-Matapédia",
      "Saint-François-d'Assise",
      "Saint-Jean-de-Cherbourg",
      "Saint-Moïse",
      "Saint-Zénon-du-Lac-Humqui",
      "Sayabec",
      "Val-Brillant",
    ],
  },
  {
    label: "Nord-du-Québec",
    cities: [
      "Chibougamau",
      "Chapais",
      "Lebel-sur-Quévillon",
      "Matagami",
      "Nemaska",
      "Radisson",
      "Val-d'Or",
      "Waswanipi",
      "Waskaganish",
      "Wemindji",
      "Whapmagoostui",
      "Eastmain",
      "Mistissini",
      "Oujé-Bougoumou",
      "Kuujjuaq",
      "Kuujjuarapik",
      "Akulivik",
      "Aupaluk",
      "Inukjuak",
      "Ivujivik",
      "Kangiqsualujjuaq",
      "Kangiqsujuaq",
      "Kangirsuk",
      "Quaqtaq",
      "Salluit",
      "Tasiujaq",
      "Umiujaq",
      "Puvirnituq",
      "Akulivik",
    ],
  },
] as const;

/** Unique cities, sorted for typeahead / validation (fr-CA collation). */
function buildSortedUniqueCities(groups: readonly QuebecRegionGroup[]): string[] {
  const set = new Set<string>();
  for (const g of groups) {
    for (const c of g.cities) {
      set.add(c);
    }
  }
  return [...set].sort((a, b) => a.localeCompare(b, "fr-CA", { sensitivity: "base" }));
}

const _SORTED = buildSortedUniqueCities(QUEBEC_CITY_GROUPS);

/** All Québec localités in the catalog (deduplicated). */
export const MARKET_CITIES = _SORTED as unknown as readonly string[];

export type MarketCity = string;

export function isMarketCity(value: string): value is MarketCity {
  return _SORTED.includes(value);
}
