import {
  BnhubFraudFlagStatus,
  BnhubFraudSeverity,
  BnhubTrustRiskFlagTypeV2,
  BnhubTrustRiskFlagVisibility,
} from "@prisma/client";
import { prisma } from "@/lib/db";
import { logRiskAction, logTrustAudit } from "@/modules/bnhub-trust/services/trustDecisionAuditService";
import { BnhubTrustIdentityAuditActor } from "@prisma/client";

export async function createRiskFlag(params: {
  listingId?: string | null;
  userId?: string | null;
  bookingId?: string | null;
  flagType: BnhubTrustRiskFlagTypeV2;
  severity: BnhubFraudSeverity;
  summary: string;
  evidence?: Record<string, unknown>;
  visibilityScope?: BnhubTrustRiskFlagVisibility;
  autoGenerated?: boolean;
  /** Dedupe: skip if open flag same type exists for listing */
  dedupeListing?: boolean;
}): Promise<{ id: string; created: boolean }> {
  if (params.dedupeListing && params.listingId) {
    const existing = await prisma.bnhubTrustRiskFlag.findFirst({
      where: {
        listingId: params.listingId,
        flagType: params.flagType,
        flagStatus: { in: [BnhubFraudFlagStatus.OPEN, BnhubFraudFlagStatus.UNDER_REVIEW] },
      },
    });
    if (existing) return { id: existing.id, created: false };
  }

  const row = await prisma.bnhubTrustRiskFlag.create({
    data: {
      listingId: params.listingId ?? undefined,
      userId: params.userId ?? undefined,
      bookingId: params.bookingId ?? undefined,
      flagType: params.flagType,
      severity: params.severity,
      visibilityScope: params.visibilityScope ?? BnhubTrustRiskFlagVisibility.ADMIN_ONLY,
      summary: params.summary,
      evidenceJson: (params.evidence ?? {}) as object,
      autoGenerated: params.autoGenerated ?? true,
    },
  });
  if (params.listingId) {
    await logRiskAction({
      actorType: BnhubTrustIdentityAuditActor.SYSTEM,
      listingId: params.listingId,
      actionType: "risk_flag_created",
      actionSummary: params.summary,
      after: { flagId: row.id, flagType: params.flagType },
    });
  }
  return { id: row.id, created: true };
}

export async function resolveRiskFlag(flagId: string, adminUserId: string) {
  const row = await prisma.bnhubTrustRiskFlag.update({
    where: { id: flagId },
    data: { flagStatus: BnhubFraudFlagStatus.RESOLVED },
  });
  await logTrustAudit({
    actorType: BnhubTrustIdentityAuditActor.ADMIN,
    actorId: adminUserId,
    entityType: "risk_flag",
    entityId: flagId,
    actionType: "resolved",
    actionSummary: `Flag resolved (listing ${row.listingId ?? "n/a"})`,
  });
}

export async function dismissRiskFlag(flagId: string, adminUserId: string) {
  const row = await prisma.bnhubTrustRiskFlag.update({
    where: { id: flagId },
    data: { flagStatus: BnhubFraudFlagStatus.DISMISSED },
  });
  await logTrustAudit({
    actorType: BnhubTrustIdentityAuditActor.ADMIN,
    actorId: adminUserId,
    entityType: "risk_flag",
    entityId: flagId,
    actionType: "dismissed",
    actionSummary: `Flag dismissed (listing ${row.listingId ?? "n/a"})`,
  });
}

export async function escalateRiskFlag(flagId: string, adminUserId: string) {
  const row = await prisma.bnhubTrustRiskFlag.update({
    where: { id: flagId },
    data: { flagStatus: BnhubFraudFlagStatus.ESCALATED },
  });
  await logTrustAudit({
    actorType: BnhubTrustIdentityAuditActor.ADMIN,
    actorId: adminUserId,
    entityType: "risk_flag",
    entityId: flagId,
    actionType: "escalated",
    actionSummary: `Flag escalated (listing ${row.listingId ?? "n/a"})`,
  });
}

export async function listFlagsForAdmin(take = 100) {
  return prisma.bnhubTrustRiskFlag.findMany({
    orderBy: { createdAt: "desc" },
    take,
    include: {
      listing: { select: { id: true, title: true, city: true } },
    },
  });
}

export async function listSafeFlagsForHost(hostUserId: string) {
  const listings = await prisma.shortTermListing.findMany({
    where: { ownerId: hostUserId },
    select: { id: true },
  });
  const ids = listings.map((l) => l.id);
  return prisma.bnhubTrustRiskFlag.findMany({
    where: {
      listingId: { in: ids },
      visibilityScope: BnhubTrustRiskFlagVisibility.SAFE_HOST_VISIBLE,
      flagStatus: { in: [BnhubFraudFlagStatus.OPEN, BnhubFraudFlagStatus.UNDER_REVIEW] },
    },
    select: {
      id: true,
      listingId: true,
      flagType: true,
      summary: true,
      createdAt: true,
    },
  });
}
