"use client";

import { TurboDraftSection } from "@/modules/turbo-form-drafting/types";
import { cn } from "@/lib/utils";
import { ExplainClauseButton } from "../trust-hub/ExplainClauseButton";

interface Props {
  sections: TurboDraftSection[];
  styleValidation?: any;
  draftId?: string;
}

export function TurboDraftPreview({ sections, styleValidation, draftId }: Props) {
  if (sections.length === 0) return null;

  return (
    <div className="space-y-8">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-4">
          <p className="text-[10px] font-black uppercase tracking-widest text-neutral-500">Draft Document Preview</p>
          {styleValidation && (
            <div className="flex gap-2">
              {styleValidation.sections.missingSections.length === 0 ? (
                <span className="rounded-full bg-emerald-500/10 px-2 py-0.5 text-[8px] font-bold text-emerald-500 uppercase">Structure Validée</span>
              ) : (
                <span className="rounded-full bg-red-500/10 px-2 py-0.5 text-[8px] font-bold text-red-500 uppercase">Structure Incomplète</span>
              )}
            </div>
          )}
        </div>
        <div className="flex items-center gap-2">
          <span className="flex h-1.5 w-1.5 rounded-full bg-premium-gold animate-pulse" />
          <span className="text-[8px] font-bold text-premium-gold/60 uppercase tracking-widest italic">Suggestion automatisée — à valider</span>
        </div>
      </div>

      {styleValidation && styleValidation.clauses.length > 0 && (
        <div className="rounded-2xl border border-amber-500/20 bg-amber-500/5 p-4">
          <h4 className="text-[10px] font-black uppercase tracking-widest text-amber-500 mb-2">Anomalies de rédaction détectées</h4>
          <ul className="space-y-1">
            {styleValidation.clauses.map((issue: any, idx: number) => (
              <li key={idx} className="text-[10px] text-amber-200/70 flex items-center gap-2">
                <span className="h-1 w-1 rounded-full bg-amber-500" />
                {issue.issue}
              </li>
            ))}
          </ul>
        </div>
      )}

      <div className="rounded-3xl border border-white/5 bg-black/40 p-8 shadow-2xl backdrop-blur-xl sm:p-12">
        <div className="mx-auto max-w-2xl space-y-12">
          {sections.map((section, i) => (
            <div key={i} className="space-y-6">
              <div className="flex items-center justify-between gap-4">
                <div className="flex items-center gap-4 flex-1">
                  <span className="text-sm font-black text-premium-gold/30">0{i + 1}</span>
                  <h3 className="text-xs font-black uppercase tracking-[0.3em] text-premium-gold/80">{section.title}</h3>
                  <div className="h-px flex-1 bg-white/5" />
                </div>
                <ExplainClauseButton sectionKey={section.title} clauseText={section.content} draftId={draftId} />
              </div>
              <div className="whitespace-pre-wrap text-sm leading-relaxed text-neutral-300">
                {section.content}
              </div>
            </div>
          ))}
          
          <div className="mt-12 border-t border-white/5 pt-12 text-center italic">
            <p className="text-[10px] uppercase tracking-widest text-neutral-600">
              [Document Generated by LECIPM Turbo Draft System]
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
