import { RecommendationsClient } from "./recommendations-client";

export default function AiRecommendationsPage() {
  return (
    <div>
      <h1 className="mb-2 text-lg font-semibold text-white">Recommendations</h1>
      <p className="mb-6 text-sm text-white/50">Cards generated by AI automations or tools — review before any live change.</p>
      <RecommendationsClient />
    </div>
  );
}
