import { NextResponse } from "next/server";
import { prisma } from "@/lib/db";
import { requireMortgageExpertWithTerms } from "@/modules/mortgage/services/expert-guard";

export const dynamic = "force-dynamic";

/** Download printable invoice (HTML — open in browser and print to PDF). */
export async function GET(
  _req: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  const session = await requireMortgageExpertWithTerms();
  if ("error" in session) return session.error;
  const { id } = await params;

  const inv = await prisma.expertInvoice.findFirst({
    where: { id, expertId: session.expert.id },
  });
  if (!inv) return NextResponse.json({ error: "Not found" }, { status: 404 });

  const expert = session.expert;
  const amount = (inv.amountCents / 100).toFixed(2);
  const when = inv.createdAt.toISOString().slice(0, 10);
  const title =
    inv.type === "subscription"
      ? "Subscription invoice"
      : inv.type === "lead_credits"
        ? "Lead credits receipt"
        : inv.type === "commission"
          ? "Platform commission invoice"
          : "Invoice";

  const html = `<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8"/><title>${title}</title>
<style>
  body{font-family:system-ui,Segoe UI,Roboto,sans-serif;background:#0b0b0b;color:#f5f5f5;padding:32px;max-width:720px;margin:0 auto;}
  h1{color:#C9A646;font-size:22px;margin:0 0 8px;}
  .muted{color:#a3a3a3;font-size:13px;}
  .box{border:1px solid #333;border-radius:12px;padding:20px;margin-top:24px;background:#141414;}
  .row{display:flex;justify-content:space-between;margin:8px 0;}
  .amt{font-size:28px;font-weight:700;color:#C9A646;margin-top:16px;}
  @media print{body{background:#fff;color:#000}h1{color:#000}.box{border-color:#ccc;background:#fff}}
</style></head><body>
  <h1>${title}</h1>
  <p class="muted">Invoice #${inv.id}<br/>Date: ${when}<br/>Currency: ${inv.currency.toUpperCase()}</p>
  <div class="box">
    <p><strong>Bill to</strong><br/>${expert.name}<br/>${expert.email}</p>
    <p style="margin-top:16px">${inv.description ?? inv.type}</p>
    <div class="row amt"><span>Total</span><span>$${amount}</span></div>
  </div>
  <p class="muted" style="margin-top:32px;font-size:11px;">Generated by the platform. Use your browser Print dialog to save as PDF.</p>
</body></html>`;

  return new NextResponse(html, {
    headers: {
      "Content-Type": "text/html; charset=utf-8",
      "Content-Disposition": `attachment; filename="invoice-${inv.id.slice(0, 8)}.html"`,
    },
  });
}
