/**
 * Printable listing brochure — BNHub marketing export (internal).
 */
import { Document, Page, Text, View, StyleSheet, Image } from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontSize: 10,
    fontFamily: "Helvetica",
    color: "#0b0b0b",
    backgroundColor: "#fafafa",
  },
  gold: { color: "#B8922B", fontFamily: "Helvetica-Bold" },
  h1: { fontSize: 20, fontFamily: "Helvetica-Bold", marginBottom: 6 },
  sub: { fontSize: 11, color: "#444", marginBottom: 16 },
  hero: { width: "100%", height: 160, objectFit: "cover" as const, marginBottom: 14 },
  box: {
    borderWidth: 1,
    borderColor: "#D4AF37",
    padding: 12,
    backgroundColor: "#fffdf7",
    marginBottom: 12,
  },
  row: { marginBottom: 4 },
  label: { fontSize: 8, color: "#666", textTransform: "uppercase" as const },
  footer: { marginTop: 24, fontSize: 8, color: "#888" },
});

export type BrochureListingInput = {
  title: string;
  city: string;
  listingCode: string | null;
  nightPriceCents: number;
  maxGuests: number;
  beds: number;
  baths: number;
  description: string | null;
  heroImageUrl: string | null;
  amenitiesLine: string;
  ctaUrl: string;
};

export function BnhubListingBrochureDocument(props: BrochureListingInput) {
  const price = `$${(props.nightPriceCents / 100).toFixed(0)} / night`;
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.gold}>BNHub · LECIPM</Text>
        <Text style={styles.h1}>{props.title}</Text>
        <Text style={styles.sub}>
          {props.city}
          {props.listingCode ? ` · ${props.listingCode}` : ""}
        </Text>
        {props.heroImageUrl ? <Image src={props.heroImageUrl} style={styles.hero} /> : null}
        <View style={styles.box}>
          <Text style={styles.label}>Pricing</Text>
          <Text style={{ fontSize: 14, fontFamily: "Helvetica-Bold" }}>{price}</Text>
          <Text style={{ marginTop: 6 }}>
            {props.maxGuests} guests · {props.beds} beds · {props.baths} baths
          </Text>
        </View>
        <View style={styles.box}>
          <Text style={styles.label}>Highlights</Text>
          <Text>{props.amenitiesLine || "—"}</Text>
        </View>
        <View style={{ marginBottom: 12 }}>
          <Text style={styles.label}>About</Text>
          <Text>{(props.description ?? "").slice(0, 1200) || "Ask host for details."}</Text>
        </View>
        <View style={styles.box}>
          <Text style={styles.label}>Book</Text>
          <Text>{props.ctaUrl}</Text>
        </View>
        <Text style={styles.footer}>
          Generated by BNHub Marketing Engine · For accurate availability and policies, use the live listing page.
        </Text>
      </Page>
    </Document>
  );
}
