import { prisma } from "@/lib/db";

export type CommunicationDraftHookResult = {
  subject: string;
  body: string;
  channel: "email" | "internal_note";
  requiresBrokerApproval: true;
  disclaimer: string;
};

/**
 * Returns a draft only — does not send. Optionally persists LecipmCommunicationDraft when integrated.
 */
export async function buildBrokerReviewableStatusDraft(dealId: string): Promise<CommunicationDraftHookResult> {
  const deal = await prisma.deal.findUnique({
    where: { id: dealId },
    select: { status: true, dealCode: true, buyer: { select: { name: true } }, seller: { select: { name: true } } },
  });
  const ref = deal?.dealCode ?? dealId.slice(0, 8);
  return {
    subject: `Deal ${ref} — status update (draft)`,
    body:
      `Hello,\n\nHere is a short status update on file ${ref} (current status: ${deal?.status ?? "unknown"}). ` +
      `Please reply with any questions.\n\n— Draft only; broker to review before sending.`,
    channel: "email",
    requiresBrokerApproval: true,
    disclaimer: "Draft generated by LECIPM — not sent. Route through your communication workflow.",
  };
}
