"use client";

import { useCallback, useEffect, useState } from "react";

type TunnelResult = {
  id: string;
  name: string;
  critical: boolean;
  status: "PASS" | "FAIL" | "WARNING";
  errors: string[];
  logs: string[];
};

type ReportPayload = {
  generatedAt: string;
  totalTests: number;
  passed: number;
  failed: number;
  warnings: number;
  recommendation: "GO" | "NO_GO";
  notes: string[];
  results: TunnelResult[];
};

export function AdminValidationDashboard() {
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [missing, setMissing] = useState(false);
  const [hint, setHint] = useState<string | null>(null);
  const [report, setReport] = useState<ReportPayload | null>(null);

  const load = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const res = await fetch("/api/admin/testing/report", { cache: "no-store" });
      const json = (await res.json()) as {
        ok?: boolean;
        missing?: boolean;
        hint?: string;
        report?: ReportPayload;
        error?: string;
      };
      if (!res.ok) {
        setError(json.error ?? `HTTP ${res.status}`);
        setReport(null);
        return;
      }
      if (json.missing) {
        setMissing(true);
        setHint(json.hint ?? null);
        setReport(null);
        return;
      }
      setMissing(false);
      setReport(json.report ?? null);
    } catch (e) {
      setError(e instanceof Error ? e.message : String(e));
      setReport(null);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    void load();
  }, [load]);

  return (
    <div className="mx-auto max-w-5xl px-4 py-8 text-zinc-100">
      <div className="mb-6 flex flex-wrap items-center justify-between gap-3">
        <div>
          <h1 className="text-2xl font-semibold tracking-tight">LECIPM — Full system validation</h1>
          <p className="mt-1 text-sm text-zinc-400">
            Reads the latest JSON report from <code className="text-zinc-300">tests/reports/final-report.json</code>{" "}
            (generated by the CLI). Refresh after running the suite locally or in CI.
          </p>
        </div>
        <button
          type="button"
          onClick={() => void load()}
          className="rounded-lg border border-zinc-600 bg-zinc-800 px-3 py-2 text-sm font-medium hover:bg-zinc-700"
        >
          Refresh
        </button>
      </div>

      {loading && <p className="text-zinc-400">Loading…</p>}
      {error && (
        <div className="rounded-lg border border-red-900/80 bg-red-950/40 p-4 text-red-200">{error}</div>
      )}
      {missing && !loading && (
        <div className="rounded-lg border border-amber-800/80 bg-amber-950/30 p-4 text-amber-100">
          <p className="font-medium">No report file found.</p>
          {hint && <p className="mt-2 text-sm opacity-90">{hint}</p>}
        </div>
      )}

      {report && !loading && (
        <div className="space-y-6">
          <div
            className={`rounded-lg border p-4 ${
              report.recommendation === "GO"
                ? "border-emerald-800/80 bg-emerald-950/30"
                : "border-red-800/80 bg-red-950/30"
            }`}
          >
            <p className="text-lg font-semibold">
              Decision:{" "}
              <span className={report.recommendation === "GO" ? "text-emerald-300" : "text-red-300"}>
                {report.recommendation}
              </span>
            </p>
            <p className="mt-1 text-sm text-zinc-400">
              {report.generatedAt} — passed {report.passed} / {report.totalTests}, failed {report.failed}, warnings{" "}
              {report.warnings}
            </p>
            {report.notes.map((n) => (
              <p key={n} className="mt-2 text-sm text-zinc-300">
                {n}
              </p>
            ))}
          </div>

          <div className="overflow-x-auto rounded-lg border border-zinc-800">
            <table className="w-full text-left text-sm">
              <thead className="bg-zinc-900/80 text-zinc-400">
                <tr>
                  <th className="px-3 py-2">Tunnel</th>
                  <th className="px-3 py-2">Status</th>
                  <th className="px-3 py-2">Critical</th>
                </tr>
              </thead>
              <tbody>
                {report.results.map((r) => (
                  <tr key={r.id} className="border-t border-zinc-800">
                    <td className="px-3 py-2 font-medium">{r.name}</td>
                    <td className="px-3 py-2">
                      <span
                        className={
                          r.status === "PASS"
                            ? "text-emerald-400"
                            : r.status === "FAIL"
                              ? "text-red-400"
                              : "text-amber-300"
                        }
                      >
                        {r.status}
                      </span>
                    </td>
                    <td className="px-3 py-2 text-zinc-500">{r.critical ? "yes" : "no"}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          <div className="space-y-4">
            <h2 className="text-lg font-medium">Logs (per tunnel)</h2>
            {report.results.map((r) => (
              <details key={`log-${r.id}`} className="rounded-lg border border-zinc-800 bg-zinc-950/50">
                <summary className="cursor-pointer px-3 py-2 text-sm font-medium">
                  {r.name} — {r.status}
                </summary>
                {r.errors.length > 0 && (
                  <ul className="list-disc border-t border-zinc-800 px-8 py-2 text-sm text-red-300">
                    {r.errors.map((e) => (
                      <li key={e.slice(0, 80)}>{e}</li>
                    ))}
                  </ul>
                )}
                <pre className="max-h-64 overflow-auto whitespace-pre-wrap border-t border-zinc-800 p-3 text-xs text-zinc-400">
                  {r.logs.join("\n")}
                </pre>
              </details>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
