import type { HubJourneyStep, HubKey } from "./hub-journey.types";

export type HubJourneyStepDefinition = Omit<
  HubJourneyStep,
  "status" | "completedAt" | "blockers"
>;

export function journeyBasePath(locale: string, country: string): string {
  return `/${locale}/${country}`;
}

/** Ordered step templates (status resolved at runtime). */
export const HUB_JOURNEY_DEFINITIONS: Record<HubKey, HubJourneyStepDefinition[]> = {
  buyer: [
    {
      id: "buyer-1-area",
      hub: "buyer",
      order: 1,
      title: "Choose area / city",
      description: "Pick where you want to buy so search and alerts stay relevant.",
      why: "Location drives price, inventory, and commute — it is the first filter.",
      route: undefined,
      actionLabel: "Set search area",
    },
    {
      id: "buyer-2-budget",
      hub: "buyer",
      order: 2,
      title: "Set budget and property type",
      description: "Align price range and home type with what lenders and the market support.",
      why: "Clear criteria prevent wasted tours and speed up serious offers.",
      route: undefined,
      actionLabel: "Refine criteria",
    },
    {
      id: "buyer-3-browse",
      hub: "buyer",
      order: 3,
      title: "Browse listings",
      description: "Explore active listings that match your filters.",
      why: "You build market sense before committing time to visits.",
      route: "listings",
      actionLabel: "Browse listings",
    },
    {
      id: "buyer-4-shortlist",
      hub: "buyer",
      order: 4,
      title: "Save / shortlist opportunities",
      description: "Bookmark strong fits to compare and revisit quickly.",
      why: "A shortlist keeps decisions organized when inventory moves fast.",
      route: "dashboard/buyer",
      actionLabel: "Open buyer hub",
    },
    {
      id: "buyer-5-contact",
      hub: "buyer",
      order: 5,
      title: "Request agent help / contact property",
      description: "Reach out for details, disclosures, or representation.",
      why: "Direct contact unlocks answers and next steps the listing page cannot show.",
      route: "dashboard/buyer",
      actionLabel: "Contact or request help",
    },
    {
      id: "buyer-6-viewing",
      hub: "buyer",
      order: 6,
      title: "Schedule viewing",
      description: "Book a time to see the property in person or virtually.",
      why: "Seeing the home confirms fit and reduces offer regret.",
      route: "dashboard/buyer",
      actionLabel: "Schedule viewing",
    },
    {
      id: "buyer-7-offer",
      hub: "buyer",
      order: 7,
      title: "Make offer / continue with broker",
      description: "Prepare an offer or work with your broker on terms and timing.",
      why: "Offers convert interest into a binding path to closing.",
      route: "dashboard/buyer",
      actionLabel: "Continue with broker",
    },
  ],
  seller: [
    {
      id: "seller-1-start",
      hub: "seller",
      order: 1,
      title: "Start selling flow",
      description: "Begin the guided listing or evaluation path.",
      why: "Structured onboarding captures the data buyers and compliance need.",
      route: "sell",
      actionLabel: "Start selling",
    },
    {
      id: "seller-2-details",
      hub: "seller",
      order: 2,
      title: "Add property details",
      description: "Describe beds, baths, features, and legal basics.",
      why: "Complete details improve match quality and trust.",
      route: "dashboard/seller/listings",
      actionLabel: "Edit listing",
    },
    {
      id: "seller-3-media",
      hub: "seller",
      order: 3,
      title: "Upload photos / documents",
      description: "Add photos and any required documents.",
      why: "Visual proof and paperwork reduce friction for serious buyers.",
      route: "dashboard/seller/listings",
      actionLabel: "Add media",
    },
    {
      id: "seller-3b-certificate-location",
      hub: "seller",
      order: 4,
      title: "Certificate of location coverage",
      description:
        "Structured certificate-of-location readiness for active listings — workflow metadata only.",
      why: "Cross-checks listing fields against verified certificate extracts when configured.",
      route: "dashboard/seller/listings",
      actionLabel: "Review certificate",
    },
    {
      id: "seller-4-pricing",
      hub: "seller",
      order: 5,
      title: "Review pricing guidance",
      description: "Use platform guidance to align list price with the market.",
      why: "Right pricing balances speed and proceeds.",
      route: "evaluate",
      actionLabel: "Review pricing",
    },
    {
      id: "seller-5-publish",
      hub: "seller",
      order: 6,
      title: "Publish or request broker help",
      description: "Go live or engage a broker for representation.",
      why: "Visibility or expert help moves you toward qualified interest.",
      route: "dashboard/seller/listings",
      actionLabel: "Publish or get help",
    },
    {
      id: "seller-6-inquiries",
      hub: "seller",
      order: 7,
      title: "Manage inquiries",
      description: "Respond to buyer and agent questions promptly.",
      why: "Speed signals seriousness and protects conversion.",
      route: "dashboard/seller",
      actionLabel: "View inquiries",
    },
    {
      id: "seller-7-closing",
      hub: "seller",
      order: 8,
      title: "Move toward offer / closing",
      description: "Negotiate offers and prepare for closing milestones.",
      why: "Structured progression reduces fall-through risk.",
      route: "dashboard/seller",
      actionLabel: "Track deal",
    },
  ],
  rent: [
    {
      id: "rent-1-criteria",
      hub: "rent",
      order: 1,
      title: "Set city and budget",
      description: "Define where you need to live and what you can afford monthly.",
      why: "Criteria narrow search to viable leases.",
      route: "listings",
      actionLabel: "Search rentals",
    },
    {
      id: "rent-2-browse",
      hub: "rent",
      order: 2,
      title: "Browse rental listings",
      description: "Scan available units that fit your filters.",
      why: "Volume browsing builds intuition on value for money.",
      route: "listings",
      actionLabel: "Browse",
    },
    {
      id: "rent-3-shortlist",
      hub: "rent",
      order: 3,
      title: "Shortlist",
      description: "Save units worth a closer look.",
      why: "Shortlists keep applications organized.",
      route: "dashboard/guest-hub",
      actionLabel: "Saved items",
    },
    {
      id: "rent-4-contact",
      hub: "rent",
      order: 4,
      title: "Contact landlord/agent",
      description: "Ask questions and confirm availability.",
      why: "Contact confirms fit before you invest in a visit.",
      route: "listings",
      actionLabel: "Contact",
    },
    {
      id: "rent-5-visit",
      hub: "rent",
      order: 5,
      title: "Schedule visit",
      description: "Book a time to see the unit.",
      why: "In-person checks catch issues photos miss.",
      route: "dashboard/guest-hub",
      actionLabel: "Schedule",
    },
    {
      id: "rent-6-apply",
      hub: "rent",
      order: 6,
      title: "Apply / continue discussion",
      description: "Submit an application or continue negotiating terms.",
      why: "Formal application starts the landlord review process.",
      route: "dashboard/guest-hub",
      actionLabel: "Continue",
    },
  ],
  landlord: [
    {
      id: "landlord-1-create",
      hub: "landlord",
      order: 1,
      title: "Create rental listing",
      description: "Start a draft for your rental property.",
      why: "A listing is the entry point for tenant demand.",
      route: "dashboard/seller/listings",
      actionLabel: "Create listing",
    },
    {
      id: "landlord-2-details",
      hub: "landlord",
      order: 2,
      title: "Add details and photos",
      description: "Describe the unit, rent, and add quality photos.",
      why: "Complete listings convert better and reduce unqualified tours.",
      route: "dashboard/seller/listings",
      actionLabel: "Edit listing",
    },
    {
      id: "landlord-3-publish",
      hub: "landlord",
      order: 3,
      title: "Publish listing",
      description: "Make the listing visible to renters.",
      why: "Visibility fills your funnel.",
      route: "dashboard/seller/listings",
      actionLabel: "Publish",
    },
    {
      id: "landlord-4-leads",
      hub: "landlord",
      order: 4,
      title: "Review incoming leads",
      description: "Check new inquiries and applications.",
      why: "Fast review keeps strong tenants from moving on.",
      route: "dashboard/seller",
      actionLabel: "View leads",
    },
    {
      id: "landlord-5-respond",
      hub: "landlord",
      order: 5,
      title: "Respond to prospects",
      description: "Reply with clarity and next steps.",
      why: "Responsiveness is a top tenant decision factor.",
      route: "dashboard/seller",
      actionLabel: "Respond",
    },
    {
      id: "landlord-6-shortlist",
      hub: "landlord",
      order: 6,
      title: "Shortlist tenants",
      description: "Narrow to qualified candidates.",
      why: "Focus protects your time and the unit.",
      route: "dashboard/seller",
      actionLabel: "Shortlist",
    },
    {
      id: "landlord-7-finalize",
      hub: "landlord",
      order: 7,
      title: "Finalize rental process",
      description: "Sign lease and coordinate move-in.",
      why: "Clean handoff reduces disputes.",
      route: "dashboard/seller",
      actionLabel: "Finalize",
    },
  ],
  bnhub_guest: [
    {
      id: "bn-guest-1-search",
      hub: "bnhub_guest",
      order: 1,
      title: "Search destination and dates",
      description: "Enter where and when you want to stay.",
      why: "Availability and pricing depend on dates.",
      route: "bnhub",
      actionLabel: "Search stays",
    },
    {
      id: "bn-guest-2-compare",
      hub: "bnhub_guest",
      order: 2,
      title: "Compare stays",
      description: "Review options side by side.",
      why: "Comparison surfaces the best value and fit.",
      route: "bnhub/stays",
      actionLabel: "Compare",
    },
    {
      id: "bn-guest-3-detail",
      hub: "bnhub_guest",
      order: 3,
      title: "Open stay detail",
      description: "Read rules, amenities, and host expectations.",
      why: "Details prevent surprises at check-in.",
      route: "bnhub/stays",
      actionLabel: "Open listing",
    },
    {
      id: "bn-guest-4-trust",
      hub: "bnhub_guest",
      order: 4,
      title: "Review trust / details",
      description: "Check reviews, verification, and policies.",
      why: "Trust signals reduce booking risk.",
      route: "bnhub",
      actionLabel: "Trust & policies",
    },
    {
      id: "bn-guest-5-start-booking",
      hub: "bnhub_guest",
      order: 5,
      title: "Start booking",
      description: "Select dates and start the booking flow.",
      why: "Booking locks intent before payment.",
      route: "bnhub/stays",
      actionLabel: "Book",
    },
    {
      id: "bn-guest-6-complete",
      hub: "bnhub_guest",
      order: 6,
      title: "Complete booking",
      description: "Confirm and pay per checkout instructions.",
      why: "Payment confirms the reservation.",
      route: "bnhub/trips",
      actionLabel: "Complete checkout",
    },
    {
      id: "bn-guest-7-manage",
      hub: "bnhub_guest",
      order: 7,
      title: "Manage stay / review",
      description: "Access trip details and leave a review after stay.",
      why: "Reviews close the loop for hosts and future guests.",
      route: "bnhub/trips",
      actionLabel: "Trips",
    },
  ],
  bnhub_host: [
    {
      id: "bn-host-1-profile",
      hub: "bnhub_host",
      order: 1,
      title: "Create host profile / listing",
      description: "Set up your host presence and first stay listing.",
      why: "A listing is required to receive bookings.",
      route: "bnhub/host/listings/new",
      actionLabel: "Create listing",
    },
    {
      id: "bn-host-2-details",
      hub: "bnhub_host",
      order: 2,
      title: "Add photos / amenities / rules",
      description: "Show the space clearly and set house rules.",
      why: "Rich listings convert browsers to guests.",
      route: "bnhub/host/dashboard",
      actionLabel: "Edit listing",
    },
    {
      id: "bn-host-3-publish",
      hub: "bnhub_host",
      order: 3,
      title: "Publish stay",
      description: "Submit for review and go live when approved.",
      why: "Published inventory can be booked.",
      route: "bnhub/host/dashboard",
      actionLabel: "Publish",
    },
    {
      id: "bn-host-4-performance",
      hub: "bnhub_host",
      order: 4,
      title: "Review host performance",
      description: "Check views, conversion, and guest feedback.",
      why: "Data shows what to improve next.",
      route: "bnhub/host/dashboard",
      actionLabel: "Dashboard",
    },
    {
      id: "bn-host-5-quality",
      hub: "bnhub_host",
      order: 5,
      title: "Improve listing quality",
      description: "Upgrade photos, pricing, and description based on gaps.",
      why: "Quality lifts ranking and booking rate.",
      route: "bnhub/host/listings/new",
      actionLabel: "Improve listing",
    },
    {
      id: "bn-host-6-bookings",
      hub: "bnhub_host",
      order: 6,
      title: "Manage bookings",
      description: "Confirm, message, and prepare for guests.",
      why: "Operational excellence drives reviews.",
      route: "bnhub/host/dashboard",
      actionLabel: "Bookings",
    },
    {
      id: "bn-host-7-grow",
      hub: "bnhub_host",
      order: 7,
      title: "Optimize pricing / trust / growth",
      description: "Tune pricing, respond fast, and build trust signals.",
      why: "Sustained growth compounds on the marketplace.",
      route: "bnhub/host/dashboard",
      actionLabel: "Grow",
    },
  ],
  broker: [
    {
      id: "broker-1-profile",
      hub: "broker",
      order: 1,
      title: "Set up broker profile",
      description: "Complete profile, licensing, and visibility settings.",
      why: "Trust and routing depend on a credible profile.",
      route: "dashboard/broker",
      actionLabel: "Profile",
    },
    {
      id: "broker-2-marketplace",
      hub: "broker",
      order: 2,
      title: "Access lead marketplace / dashboard",
      description: "Open your broker hub and lead sources.",
      why: "Central hub is where pipeline work happens.",
      route: "dashboard/broker",
      actionLabel: "Open hub",
    },
    {
      id: "broker-3-unlocked",
      hub: "broker",
      order: 3,
      title: "Review unlocked leads",
      description: "Prioritize new unlocked opportunities.",
      why: "Speed matters for conversion on fresh leads.",
      route: "dashboard/broker",
      actionLabel: "Review leads",
    },
    {
      id: "broker-3b-certificate-workflow",
      hub: "broker",
      order: 4,
      title: "Certificate of location checks",
      description: "Log requests, reviews, or admin escalations for certificate coverage (metadata only).",
      why: "Structured title and lot checks reduce avoidable surprises before offers.",
      route: "dashboard/broker",
      actionLabel: "Certificate workflow",
    },
    {
      id: "broker-4-contact",
      hub: "broker",
      order: 5,
      title: "Contact leads fast",
      description: "Reach out within minutes with a clear next step.",
      why: "First response time correlates with wins.",
      route: "dashboard/broker",
      actionLabel: "Contact",
    },
    {
      id: "broker-5-pipeline",
      hub: "broker",
      order: 6,
      title: "Move leads through pipeline",
      description: "Update stages, tasks, and follow-ups.",
      why: "Pipeline hygiene prevents leakage.",
      route: "dashboard/broker",
      actionLabel: "Pipeline",
    },
    {
      id: "broker-6-closings",
      hub: "broker",
      order: 7,
      title: "Track closings",
      description: "Monitor active deals toward closing.",
      why: "Closing focus protects revenue.",
      route: "dashboard/broker",
      actionLabel: "Deals",
    },
    {
      id: "broker-7-rank",
      hub: "broker",
      order: 8,
      title: "Improve ranking / performance",
      description: "Review metrics and platform guidance to improve.",
      why: "Performance feeds future lead flow.",
      route: "dashboard/broker",
      actionLabel: "Performance",
    },
  ],
  investor: [
    {
      id: "inv-1-goals",
      hub: "investor",
      order: 1,
      title: "Define investment goals",
      description: "Set return, risk, and horizon preferences.",
      why: "Goals filter opportunities and analysis.",
      route: "dashboard/investor",
      actionLabel: "Set goals",
    },
    {
      id: "inv-2-browse",
      hub: "investor",
      order: 2,
      title: "Browse opportunities",
      description: "Scan listings and programs aligned to your thesis.",
      why: "Volume builds pattern recognition.",
      route: "listings",
      actionLabel: "Browse",
    },
    {
      id: "inv-3-insights",
      hub: "investor",
      order: 3,
      title: "Review AI / investor insights",
      description: "Use platform insights to stress-test assumptions.",
      why: "Structured insight reduces blind spots.",
      route: "dashboard/investor",
      actionLabel: "Insights",
    },
    {
      id: "inv-4-shortlist",
      hub: "investor",
      order: 4,
      title: "Shortlist properties",
      description: "Save candidates for deeper work.",
      why: "Shortlists keep diligence organized.",
      route: "dashboard/investor",
      actionLabel: "Shortlist",
    },
    {
      id: "inv-5-analysis",
      hub: "investor",
      order: 5,
      title: "Request deeper analysis / broker contact",
      description: "Engage experts or run deeper models.",
      why: "Large checks deserve verification.",
      route: "dashboard/investor",
      actionLabel: "Request analysis",
    },
    {
      id: "inv-6-compare",
      hub: "investor",
      order: 6,
      title: "Compare opportunities",
      description: "Compare deals on key financial metrics.",
      why: "Comparison clarifies trade-offs.",
      route: "dashboard/investor",
      actionLabel: "Compare",
    },
    {
      id: "inv-7-action",
      hub: "investor",
      order: 7,
      title: "Move toward offer / investment action",
      description: "Prepare LOI, offer, or allocation when ready.",
      why: "Decisive action captures opportunity windows.",
      route: "dashboard/investor",
      actionLabel: "Take action",
    },
  ],
  admin: [
    {
      id: "adm-1-dashboard",
      hub: "admin",
      order: 1,
      title: "Review mission control / dashboard",
      description: "Scan system health and operational snapshot.",
      why: "Top-level view sets daily priorities.",
      route: "admin/dashboard",
      actionLabel: "Dashboard",
    },
    {
      id: "adm-2-revenue",
      hub: "admin",
      order: 2,
      title: "Review revenue + funnel + broker performance",
      description: "Inspect revenue drivers and broker outcomes.",
      why: "Revenue and funnel explain growth constraints.",
      route: "admin/revenue-dashboard",
      actionLabel: "Revenue",
    },
    {
      id: "adm-3-governance",
      hub: "admin",
      order: 3,
      title: "Review alerts / governance / policy",
      description: "Check alerts, compliance, and policy status.",
      why: "Governance prevents operational and legal drift.",
      route: "admin/dashboard",
      actionLabel: "Governance",
    },
    {
      id: "adm-4-leads",
      hub: "admin",
      order: 4,
      title: "Review lead quality / routing / pricing",
      description: "Audit lead flow, routing rules, and monetization.",
      why: "Lead economics underpin marketplace liquidity.",
      route: "admin/crm-live",
      actionLabel: "CRM / leads",
    },
    {
      id: "adm-5-bnhub",
      hub: "admin",
      order: 5,
      title: "Review BNHub marketplace health",
      description: "Monitor stays, disputes, and host quality signals.",
      why: "Travel marketplace health is cross-functional.",
      route: "admin/dashboard",
      actionLabel: "BNHub",
    },
    {
      id: "adm-6-growth",
      hub: "admin",
      order: 6,
      title: "Review growth actions",
      description: "Review experiments, campaigns, and Growth OS backlog.",
      why: "Growth compounds when experiments are visible.",
      route: "admin/growth-dashboard",
      actionLabel: "Growth",
    },
    {
      id: "adm-7-execute",
      hub: "admin",
      order: 7,
      title: "Execute approved actions / monitor results",
      description: "Ship approved changes and watch metrics.",
      why: "Execution closes the loop on strategy.",
      route: "admin/dashboard",
      actionLabel: "Execute",
    },
  ],
};

export function getHubPlanMeta(hub: HubKey): { title: string; description: string } {
  const meta: Record<HubKey, { title: string; description: string }> = {
    buyer: {
      title: "Buyer journey",
      description: "From search to offer — stay oriented at every step.",
    },
    seller: {
      title: "Seller journey",
      description: "From listing prep to closing — know what comes next.",
    },
    rent: {
      title: "Rent journey",
      description: "Find and secure a lease with clear milestones.",
    },
    landlord: {
      title: "Landlord journey",
      description: "Publish, qualify, and close on a great tenant.",
    },
    bnhub_guest: {
      title: "BNHub guest journey",
      description: "Search, book, and enjoy your stay with confidence.",
    },
    bnhub_host: {
      title: "BNHub host journey",
      description: "List, optimize, and grow on the marketplace.",
    },
    broker: {
      title: "Broker journey",
      description: "Profile, leads, pipeline, and closings in one flow.",
    },
    investor: {
      title: "Investor journey",
      description: "Goals, diligence, and decisive action.",
    },
    admin: {
      title: "Operator journey",
      description: "Mission control for revenue, governance, and growth.",
    },
  };
  return meta[hub];
}

/** Resolve relative route segments: `admin/*` is global; everything else is under `/{locale}/{country}/`. */
export function resolveStepRoute(
  segment: string | undefined,
  locale: string,
  country: string,
): string | undefined {
  if (!segment) return undefined;
  if (segment.startsWith("http")) return segment;
  const s = segment.replace(/^\//, "");
  if (s.startsWith("admin/")) return `/${s}`;
  return `${journeyBasePath(locale, country)}/${s}`;
}
