/**
 * Authoritative copy for admin / import; safe defaults use RECOMMEND_ONLY or HUMAN_APPROVAL.
 * `actionType` matches execution adapter allow-list.
 */
export const dreamHomePlaybookSeeds = [
  {
    key: "wave11_dream_home_pref_match_v1",
    name: "Preference match (recommendation + ranking)",
    domain: "DREAM_HOME" as const,
    actionType: "dream_home_recommend_playbook",
    description: "Surfaces homes from user-stated preferences; ranking and filters only; no messaging.",
    segmentScope: { sources: ["dream_home_wizard"] },
    marketScope: null,
    objectives: { primary: "increase_relevant_listing_views", secondary: "transparent_explanations" },
    successCriteria: { minClickThrough: 0.15, minSavedListings: 0.02 },
    currentVersionConfigPlaceholder: { model: "context_fit_v1" },
    safeExecutionModeDefault: "RECOMMEND_ONLY" as const,
  },
  {
    key: "family_space_priority_v1",
    name: "Family & space function",
    domain: "DREAM_HOME" as const,
    actionType: "dream_home_recommend_playbook",
    description: "Prioritizes bedroom count, storage, and layout flow for multi-person households (declared needs only).",
    segmentScope: { familySizeBand: ["medium", "large"] },
    marketScope: { optional: true },
    objectives: { primary: "layout_fit", secondary: "reduce_mismatch_bounces" },
    successCriteria: { minDetailDepth: 0.2 },
    currentVersionConfigPlaceholder: { model: "family_bedroom_v1" },
    safeExecutionModeDefault: "RECOMMEND_ONLY" as const,
  },
  {
    key: "privacy_first_layout_v1",
    name: "Privacy-first layout",
    domain: "DREAM_HOME" as const,
    actionType: "dream_home_recommend_playbook",
    description: "Nudges toward separated zones and quieter placement when user sets privacy to high.",
    segmentScope: { privacyPreference: "high" },
    objectives: { primary: "user_stated_privacy" },
    successCriteria: { minShortlist: 0.01 },
    currentVersionConfigPlaceholder: { model: "privacy_layout_v1" },
    safeExecutionModeDefault: "HUMAN_APPROVAL" as const,
  },
  {
    key: "hosting_friendly_home_v1",
    name: "Hosting-friendly home",
    domain: "DREAM_HOME" as const,
    actionType: "dream_home_recommend_playbook",
    description: "Kitchen + gathering space emphasis when hosting frequency or priority is high (explicit fields).",
    segmentScope: { hostingLevel: ["medium", "high"] },
    objectives: { primary: "gathering_space_fit" },
    successCriteria: { minInquiry: 0.01 },
    currentVersionConfigPlaceholder: { model: "hosting_v1" },
    safeExecutionModeDefault: "RECOMMEND_ONLY" as const,
  },
  {
    key: "work_from_home_balance_v1",
    name: "Work-from-home balance",
    domain: "DREAM_HOME" as const,
    actionType: "dream_home_recommend_playbook",
    description: "Workable office / quiet space cues when WFH is sometimes or full_time (user-declared).",
    segmentScope: { workFromHome: ["sometimes", "full_time"] },
    objectives: { primary: "workspace_separation" },
    successCriteria: { minSessionDepth: 0.2 },
    currentVersionConfigPlaceholder: { model: "wfh_v1" },
    safeExecutionModeDefault: "RECOMMEND_ONLY" as const,
  },
  {
    key: "multigenerational_living_v1",
    name: "Multigenerational or extended household",
    domain: "DREAM_HOME" as const,
    actionType: "dream_home_recommend_playbook",
    description: "Extra bedroom / suite potential when elders in home or high guest frequency is set.",
    segmentScope: { eldersInHome: true, guestsFrequency: ["medium", "high"] },
    objectives: { primary: "sleeping_room_count" },
    successCriteria: { minVisitBook: 0.005 },
    currentVersionConfigPlaceholder: { model: "multigen_v1" },
    safeExecutionModeDefault: "HUMAN_APPROVAL" as const,
  },
  {
    key: "accessibility_support_v1",
    name: "Accessibility & mobility support",
    domain: "DREAM_HOME" as const,
    actionType: "dream_home_recommend_playbook",
    description: "Surfaces single-level or lift-friendly language in listings when user lists accessibility needs.",
    segmentScope: { accessibilityNeedsMin: 1 },
    objectives: { primary: "a11y_signal_match" },
    successCriteria: { minPositiveFeedback: 0.1 },
    currentVersionConfigPlaceholder: { model: "a11y_v1" },
    safeExecutionModeDefault: "HUMAN_APPROVAL" as const,
  },
] as const;
