import { getGuestId } from "@/lib/auth/session";
import { getLegacyDB } from "@/lib/db/legacy";
const prisma = getLegacyDB();
import { createRiskFlag } from "@/modules/bnhub-trust/services/riskFlagService";
import { BnhubFraudSeverity, BnhubTrustRiskFlagTypeV2 } from "@prisma/client";

export const dynamic = "force-dynamic";

const MAX_NOTE = 500;

export async function POST(req: Request, ctx: { params: Promise<{ id: string }> }) {
  const userId = await getGuestId();
  if (!userId) return Response.json({ error: "Unauthorized" }, { status: 401 });
  const listingId = (await ctx.params).id;
  const listing = await prisma.shortTermListing.findUnique({
    where: { id: listingId },
    select: { id: true },
  });
  if (!listing) return Response.json({ error: "Not found" }, { status: 404 });

  let note = "";
  try {
    const b = await req.json();
    note = typeof b.note === "string" ? b.note.trim().slice(0, MAX_NOTE) : "";
  } catch {
    /* empty */
  }
  if (note.length < 8) {
    return Response.json({ error: "note required (min 8 characters)" }, { status: 400 });
  }

  const { id, created } = await createRiskFlag({
    listingId,
    userId,
    flagType: BnhubTrustRiskFlagTypeV2.MANUAL_REVIEW,
    severity: BnhubFraudSeverity.MEDIUM,
    summary: "Guest reported a concern — additional validation may be required.",
    evidence: { source: "guest_report", reporterUserId: userId, note },
    autoGenerated: false,
    dedupeListing: false,
  });

  return Response.json({
    ok: true,
    flagId: id,
    created,
    message: "Thank you — our team will review using internal tools only.",
  });
}
