/**
 * Hub navigation items – links per hub.
 *
 * Platform grouping (product):
 * - **BNHUB** — short-term stays, guest tools, host/hotel/motel dashboard, trips & travel AI.
 * - **Immobilier Hub** (`realEstate` key) — long-term rent, broker-guided and FSBO sales, buyer/seller workspaces.
 * - **Financial Hub** (`financialHub` key) — mortgage tools, specialist desk, AI pricing, buyer calculators.
 */

export type NavItem = { label: string; href: string };

export const hubNavigation: Record<string, NavItem[]> = {
  bnhub: [
    { label: "BNHUB home", href: "/bnhub" },
    { label: "Guest dashboard", href: "/dashboard/bnhub" },
    { label: "Find a stay", href: "/search/bnhub" },
    { label: "Trips", href: "/bnhub/trips" },
    { label: "Travel AI", href: "/bnhub/travel/compare" },
    { label: "Host dashboard", href: "/bnhub/host/dashboard" },
    { label: "BNHUB Marketing", href: "/bnhub/host/marketing" },
    { label: "Growth & leads", href: "/bnhub/host/growth" },
    { label: "Onboarding", href: "/onboarding/bnhub" },
    { label: "Contracts", href: "/dashboard/contracts" },
  ],
  realEstate: [
    { label: "Immobilier Hub — home", href: "/dashboard/real-estate" },
    { label: "Long-term rent", href: "/rent" },
    { label: "Buyer workspace", href: "/dashboard/buyer" },
    { label: "Sell with broker (guided)", href: "/sell" },
    { label: "Sell yourself (FSBO)", href: "/dashboard/fsbo" },
    { label: "Broker workspace", href: "/dashboard/broker" },
    { label: "Compliance", href: "/dashboard/compliance" },
    { label: "Compare listings", href: "/compare/fsbo" },
    { label: "Daily run", href: "/dashboard/daily-execution" },
    { label: "Command center", href: "/dashboard/command" },
    { label: "Workspace", href: "/dashboard/tenant" },
    { label: "Finance", href: "/dashboard/finance" },
    { label: "Notifications", href: "/dashboard/notifications" },
    { label: "Tasks", href: "/dashboard/tasks" },
    { label: "Client intake", href: "/dashboard/intake" },
    { label: "Appointments", href: "/dashboard/appointments" },
    { label: "Deals", href: "/dashboard/deals" },
    { label: "Deal rooms", href: "/dashboard/deal-rooms" },
    { label: "ImmoContact deal rooms", href: "/dashboard/immo-deal-rooms" },
    { label: "Listings", href: "/dashboard/listings" },
    { label: "Leads", href: "/dashboard/leads" },
    { label: "Forms", href: "/forms" },
    { label: "Onboarding", href: "/onboarding/realestate" },
    { label: "Contracts", href: "/dashboard/contracts" },
    { label: "Storage", href: "/dashboard/storage" },
    { label: "Billing", href: "/dashboard/billing" },
  ],
  financialHub: [
    { label: "Financial Hub — home", href: "/financial-hub" },
    { label: "Mortgage page & calculator", href: "/mortgage" },
    { label: "Mortgage specialist desk", href: "/dashboard/expert" },
    { label: "Mortgage hub (unlock)", href: "/dashboard/mortgage" },
    { label: "Insurance", href: "/dashboard/insurance" },
    { label: "Broker partner program", href: "/mortgage/for-brokers" },
    { label: "Appraisal calculator", href: "/appraisal-calculator" },
    { label: "ROI calculator", href: "/tools/roi-calculator" },
    { label: "Seller valuation", href: "/evaluate" },
    { label: "Immobilier finance", href: "/dashboard/finance" },
  ],
  luxury: [
    { label: "Dashboard", href: "/dashboard/luxury" },
    { label: "Listings", href: "/dashboard/listings" },
    { label: "Onboarding", href: "/onboarding/luxury" },
    { label: "Contracts", href: "/dashboard/contracts" },
    { label: "Forms", href: "/forms" },
    { label: "Design templates", href: "/design-templates" },
    { label: "Marketing", href: "/dashboard/billing" },
  ],
  broker: [
    { label: "Dashboard", href: "/dashboard/broker" },
    { label: "Deal pipeline", href: "/dashboard/broker/deal-lifecycle" },
    { label: "ESG dashboard", href: "/dashboard/esg" },
    { label: "Autonomy ops", href: "/dashboard/autonomy" },
    { label: "Listing inbox", href: "/dashboard/messages" },
    { label: "Inquiry CRM (AI)", href: "/dashboard/crm" },
    { label: "CRM Autopilot", href: "/dashboard/crm/autopilot" },
    { label: "Visits", href: "/dashboard/visits" },
    { label: "Deal rooms", href: "/dashboard/deal-rooms" },
    { label: "ImmoContact deal rooms", href: "/dashboard/immo-deal-rooms" },
    { label: "Workspace", href: "/dashboard/tenant" },
    { label: "Finance", href: "/dashboard/finance" },
    { label: "Notifications", href: "/dashboard/notifications" },
    { label: "Tasks", href: "/dashboard/tasks" },
    { label: "Broker CRM", href: "/dashboard/broker/crm" },
    { label: "Clients", href: "/dashboard/broker/clients" },
    { label: "Client intake", href: "/dashboard/broker/intake" },
    { label: "Compliance", href: "/dashboard/compliance" },
    { label: "Pipeline", href: "/dashboard/broker#immo-leads" },
    { label: "CRM tasks", href: "/dashboard/broker/tasks" },
    { label: "Calendar", href: "/dashboard/broker/calendar" },
    { label: "Availability", href: "/dashboard/broker/calendar/availability" },
    { label: "AI follow-up", href: "/dashboard/broker/ai-follow-up" },
    { label: "AI leads", href: "/dashboard/broker/ai-leads" },
    { label: "Content studio", href: "/dashboard/broker/content-studio" },
    { label: "Daily run", href: "/dashboard/daily-execution" },
    { label: "AI Operator", href: "/dashboard/ai-operator" },
    { label: "Conversion funnel", href: "/dashboard/broker/conversion-funnel" },
    { label: "Centris conversion", href: "/dashboard/broker/centris-conversion" },
    { label: "Lifecycle CRM", href: "/dashboard/broker/lifecycle" },
    { label: "Market AI", href: "/dashboard/broker/market-insights" },
    { label: "Deals", href: "/dashboard/deals" },
    { label: "Commissions", href: "/dashboard/broker/commissions" },
    { label: "Tax (GST/QST)", href: "/dashboard/broker/tax-information" },
    { label: "Leads", href: "/dashboard/leads" },
    { label: "Listings", href: "/dashboard/listings" },
    { label: "Onboarding", href: "/onboarding/broker" },
    { label: "Contracts", href: "/dashboard/contracts" },
    { label: "Contracts & offers", href: "/dashboard/broker/contracts-offers" },
    { label: "Broker messages", href: "/dashboard/broker/messages" },
    { label: "Billing", href: "/dashboard/billing" },
  ],
  investments: [
    { label: "Command center", href: "/dashboard/command" },
    { label: "Dashboard", href: "/dashboard/investments" },
    { label: "Investor hub", href: "/dashboard/investor" },
    { label: "Deals", href: "/marketplace" },
    { label: "Analytics", href: "/dashboard/investments" },
    { label: "Investor tools", href: "/invest/tools" },
    { label: "ROI calculator", href: "/invest/tools/roi" },
    { label: "Portfolio planner", href: "/invest/portfolio" },
    { label: "Market trends", href: "/market" },
  ],
  referrals: [
    { label: "Dashboard", href: "/dashboard/referrals" },
    { label: "Ambassador", href: "/dashboard/ambassador" },
    { label: "Leaderboard", href: "/dashboard/referrals/leaderboard" },
  ],
  projects: [
    { label: "Dashboard", href: "/dashboard/projects" },
    { label: "All projects", href: "/projects" },
    { label: "Onboarding", href: "/onboarding/projects" },
    { label: "Contracts", href: "/dashboard/contracts" },
    { label: "Favorites", href: "/dashboard/projects/favorites" },
    { label: "Alerts", href: "/dashboard/projects/alerts" },
    { label: "Reservations", href: "/dashboard/projects/reservations" },
  ],
  admin: [
    { label: "Management Hub", href: "/admin/management-hub" },
    { label: "Control center", href: "/admin/dashboard" },
    { label: "AI assistant", href: "/admin/assistant" },
    { label: "Platform controls", href: "/admin/controls" },
    { label: "Platform improvement review", href: "/admin/platform-improvement" },
    { label: "Global timeline", href: "/admin/timeline" },
    { label: "Code lookup", href: "/admin/lookup" },
    { label: "Contracts", href: "/admin/contracts" },
    { label: "ImmoContact", href: "/admin/immo-contact" },
    { label: "Finance", href: "/admin/finance" },
    { label: "Broker billing (how you get paid)", href: "/admin/broker-billing" },
    { label: "GST / QST", href: "/admin/finance/taxes" },
    { label: "Host payouts", href: "/admin/payouts" },
    { label: "Disputes", href: "/admin/disputes" },
    { label: "Listings hub", href: "/admin/listings" },
    { label: "Deals hub", href: "/admin/deals" },
    { label: "Compliance & QA", href: "/admin/compliance" },
    { label: "Immo contacts", href: "/admin/immocontacts" },
    { label: "ImmoContact logs", href: "/admin/immo-logs" },
    { label: "Enforceable contracts", href: "/admin/enforceable-contracts" },
    { label: "Legal & finance", href: "/admin/legal-finance" },
    { label: "Calendars", href: "/admin/calendars" },
    { label: "Reports hub", href: "/admin/reports" },
    { label: "AI insights", href: "/admin/ai-insights" },
    { label: "Content ops", href: "/admin/content-ops" },
    { label: "Content generator (TikTok)", href: "/admin/content-generator" },
    { label: "Social connections", href: "/admin/social" },
    { label: "Autonomous system", href: "/admin/autonomous-system" },
    { label: "Content intelligence", href: "/admin/content-intelligence" },
    { label: "Model validation", href: "/admin/model-validation" },
    { label: "System validation", href: "/admin/system-validation" },
    { label: "Calibration health", href: "/admin/calibration" },
    { label: "Model tuning", href: "/admin/model-tuning" },
    { label: "AI risk monitoring", href: "/admin/risk-monitoring" },
    { label: "TrustGraph", href: "/admin/trustgraph" },
    { label: "Moderation", href: "/admin/moderation" },
    { label: "Overview (legacy)", href: "/admin" },
    { label: "Notifications", href: "/dashboard/notifications" },
    { label: "Tasks", href: "/dashboard/tasks" },
    { label: "Staging demo", href: "/admin/demo" },
    { label: "Users", href: "/admin/users" },
    { label: "Payments", href: "/admin/finance/overview" },
    { label: "Revenue & ledger", href: "/admin/revenue" },
    { label: "Investor command center", href: "/admin/investor" },
    { label: "Revenue optimization", href: "/admin/revenue-optimization" },
    { label: "Monopoly mode", href: "/admin/monopoly" },
    { label: "Full funnel", href: "/admin/funnel" },
    { label: "Growth funnel data", href: "/admin/growth-funnel-data" },
    { label: "Domination hub", href: "/admin/domination" },
    { label: "Team workspace", href: "/admin/team" },
    { label: "Messaging system", href: "/admin/messaging" },
    { label: "CEO dashboard", href: "/admin/ceo" },
    { label: "Executive Control", href: "/admin/executive" },
    { label: "AI auto-reply inbox", href: "/admin/ai-inbox" },
    { label: "Auto-close (safe mode)", href: "/admin/autoclose" },
    { label: "Growth engine", href: "/admin/growth-engine" },
    { label: "AI marketing (copy)", href: "/admin/marketing" },
    { label: "Cities & rollout", href: "/admin/cities" },
    { label: "Launch tracking", href: "/admin/launch" },
    { label: "Launch: sales scripts", href: "/dashboard/admin/sales" },
    { label: "Launch: daily", href: "/dashboard/admin/daily" },
    { label: "First 10 clients", href: "/dashboard/admin/clients-acquisition" },
    { label: "Ads analytics", href: "/admin/analytics" },
    { label: "Tool analytics", href: "/admin/analytics/tools" },
    { label: "Organic analytics", href: "/admin/organic-analytics" },
    { label: "SEO blog", href: "/admin/seo-blog" },
    { label: "Internal CRM (BNHUB)", href: "/admin/crm/internal" },
    { label: "Traffic & attribution", href: "/admin/attribution" },
    { label: "Bookings", href: "/admin/bookings" },
    { label: "Revenue overview", href: "/admin/revenue-overview" },
    { label: "BNHUB revenue", href: "/admin/revenue-dashboard" },
    { label: "Map overview", href: "/admin/map-overview" },
    { label: "BNHUB issues", href: "/admin/issues" },
    { label: "BNHUB booking disputes", href: "/admin/bnhub-disputes" },
    { label: "Partner outreach (travel)", href: "/admin/partner-outreach" },
    { label: "BNHUB Marketing", href: "/admin/bnhub/marketing" },
    { label: "BNHUB campaigns", href: "/admin/bnhub/marketing/campaigns" },
    { label: "BNHUB Growth", href: "/admin/bnhub/growth" },
    { label: "Growth campaigns", href: "/admin/bnhub/growth/campaigns" },
    { label: "Growth leads", href: "/admin/bnhub/growth/leads" },
    { label: "User feedback", href: "/admin/feedback" },
    { label: "Trust & safety", href: "/admin/trust-safety" },
    { label: "Commissions", href: "/admin/commissions" },
    { label: "Finance overview", href: "/admin/finance" },
    { label: "Accounting", href: "/admin/accounting" },
    { label: "Broker payouts", href: "/admin/finance/payouts" },
    { label: "Tax documents", href: "/admin/finance/tax" },
    { label: "Reports", href: "/admin/finance/reports" },
    { label: "Broker tax (GST/QST)", href: "/admin/broker-tax" },
    { label: "Legal", href: "/admin/legal" },
    { label: "Content license", href: "/admin/content-license" },
    { label: "Law helper (AI + drafting)", href: "/admin/legal-ai" },
    { label: "Forms & filler (submissions)", href: "/admin/forms" },
    { label: "Contract template builder", href: "/admin/contracts-builder" },
    { label: "Spell dictionary", href: "/admin/spell-dictionary" },
    { label: "Immo conversations", href: "/admin/conversations" },
    { label: "Income", href: "/admin/income" },
    { label: "Projects monetization", href: "/admin/projects-monetization" },
    { label: "Storage", href: "/admin/storage" },
    { label: "Incentives config", href: "/admin/config/incentives" },
    { label: "Logs", href: "/admin/logs" },
    { label: "Market data", href: "/admin/market" },
    { label: "Insights engine", href: "/admin/insights" },
    { label: "Shared deals (viral)", href: "/admin/growth/shared-deals" },
    { label: "Investor tools", href: "/admin/investor-tools" },
    { label: "Referrals", href: "/admin/referrals" },
    { label: "Ambassadors", href: "/admin/ambassadors" },
    { label: "Ambassador payouts", href: "/admin/ambassadors/payouts" },
    { label: "Fraud alerts", href: "/admin/fraud" },
  ],
};
