/**
 * AI Operator alerts – generated by agents for human review or automation.
 */
export type AlertType =
  | "listing_quality"
  | "listing_policy"
  | "fraud_risk"
  | "booking_anomaly"
  | "demand"
  | "host_performance"
  | "support_urgent"
  | "marketplace_health"
  | "pricing";

export type AlertSeverity = "low" | "medium" | "high" | "critical";

export type AiOperatorAlert = {
  id: string;
  alertType: AlertType;
  severity: AlertSeverity;
  entityType: string;
  entityId: string;
  message: string;
  status: "open" | "acknowledged" | "resolved";
  metadata?: Record<string, unknown>;
  createdAt: string;
};
