import type { AmfExemptionCategory } from "@prisma/client";

export const LEGAL_PACK_VERSION = "2026-04-26-v1";

export const LEGAL_PACK_DISCLAIMERS = {
  notAdvice: "This document is an editable template generated by software — not legal, tax, or investment advice.",
  noGuarantee:
    "There is no guarantee of profit or return of capital. Investors may lose some or all of their investment. Past performance is not indicative of future results.",
  privatePlacement:
    "Securities are offered pursuant to private placement exemptions only. There is no public offering and no mass solicitation workflow.",
} as const;

export type SubscriptionAgreementFields = {
  spvIssuerLegalName: string;
  investorIdentity: string;
  subscribedAmount: string;
  securityType: string;
  closingConditions: string;
  investorRepresentations: string;
  governingLaw: string;
  brokerConflictNote: string;
};

export type InvestorMemoFields = {
  dealSummary: string;
  acquisitionThesis: string;
  risks: string;
  useOfProceeds: string;
  capitalStack: string;
  esgRetrofitSummary: string;
  conflictsDisclosure: string;
};

export type RiskDisclosureFields = {
  illiquidity: string;
  lossOfCapital: string;
  executionRisk: string;
  financingRisk: string;
  marketRisk: string;
  constructionRetrofitRisk: string;
  regulatoryRisk: string;
};

export type QuestionnaireFields = {
  accreditedBlock: string;
  ffbaBlock: string;
  jurisdiction: string;
  sophisticationAck: string;
};

export type ExemptionRepresentationFields = {
  exemptionReliedUpon: AmfExemptionCategory | string;
  qualificationConfirm: string;
  independentDecisionConfirm: string;
};
