export const conversionCopy = {
  heroTitles: [
    "Know if it's a good deal before you commit",
    "Analyze any property in seconds",
    "Make smarter real estate decisions instantly",
  ],
  ctas: {
    primary: ["Analyze a property", "Check this deal now"],
    secondary: ["See how it works"],
    final: "Start analyzing your first property now",
    analysisActions: ["Contact now", "Save this property", "Run another analysis"],
    propertyActions: ["Contact seller", "Request more details", "Save"],
    pricing: ["Upgrade now", "Unlock full access"],
  },
  landing: {
    headline: "Know if it's a good deal before you commit",
    subhead:
      "Get a clear trust score, deal score, and AI insights for any property - before you buy, sell, or invest.",
    ctaPrimary: "Analyze a property",
    ctaSecondary: "See how it works",
    trustLine: "Built for real-world decision making.",
    trustSection: [
      "Used by brokers and investors to avoid bad deals",
      "Built for real-world decision making",
    ],
    howItWorks: ["Add a property", "Get scores instantly", "Take action with confidence"],
  },
  onboarding: {
    welcomeTitle: "Let's analyze your first property",
    rolePrompt: "Choose your role",
    roleOptions: ["I'm a broker", "I'm an investor", "I'm selling a property", "I'm exploring"],
    propertyPrompt: "Paste a property or try a sample",
    resultPrompt: "You're ready. Let's look at your first result.",
    progressStep1: "Step 1 of 3 - Getting started",
    ctaNext: "Continue",
    ctaRun: "Run analysis",
    ctaUnlock: "Unlock full analysis",
  },
  analysis: {
    header: "Here's what we found",
    trustScoreLabel: "Trust Score",
    dealScoreLabel: "Deal Score",
    confidenceLabel: "Confidence level",
    recommendationHigh: "This looks like a strong opportunity",
    recommendationMedium: "This deal has potential, but needs review",
    recommendationLow: "This property carries risks - proceed carefully",
    keyIssues: "Issues affecting this property",
    opportunities: "Where this deal stands out",
    nextAction: "What you should do next",
    propertyPanelTitle: "Property Analysis",
    propertyBadges: ["High trust", "Needs verification", "Strong deal", "Moderate opportunity"],
  },
  upgrade: {
    title: "Unlock full decision power",
    subtitle: "Get deeper insights, better leads, and smarter tools",
    trustLine: "Cancel anytime",
    plans: {
      free: ["Basic analysis", "Limited insights"],
      pro: ["Full analysis", "CRM tools", "AI recommendations"],
      platinum: ["Priority leads", "Advanced insights", "Premium features"],
    },
    cta: "Upgrade now",
    ctaSecondary: "Unlock full access",
    lockedPrompt: "Unlock deeper insights for this property",
  },
  nudges: {
    afterAnalysis: "This deal looks promising - take action now",
    inactivity: "Still exploring? Let's find your next opportunity",
    highValue: "This could be a strong deal - don't miss it",
  },
  microcopy: {
    loading: "Analyzing property...",
    error: "Something went wrong - try again",
    empty: "Start by analyzing your first property",
    success: "Analysis complete",
  },
} as const;
