#!/usr/bin/env npx tsx
/**
 * Semi-automated model distribution: shards the monolith schema into four buckets
 * (core | listings | bnhub | compliance) for manual merge into per-module Prisma schemas.
 *
 * Does NOT fix @relation or cross-module cycles — that remains manual (see ORDER 3).
 *
 * Usage (repo root):
 *   pnpm exec tsx scripts/split-models.ts
 *   pnpm exec tsx scripts/split-models.ts --schema path/to/schema.prisma
 *
 * Default input: apps/web/prisma/schema.prisma
 * Output: packages/db-<bucket>/prisma/models.prisma + enums.prisma (same enums copied to each bucket)
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.join(__dirname, "..");

const DEFAULT_SCHEMA = path.join(REPO_ROOT, "apps/web/prisma/schema.prisma");

const BUCKETS = ["core", "listings", "bnhub", "compliance"] as const;
type Bucket = (typeof BUCKETS)[number];

const MODELS_HEADER = `// AUTO-GENERATED by scripts/split-models.ts — do not edit by hand.
// Merge into this module's schema.prisma after generator + datasource.
// Manual: fix @relation fields, remove cross-module circular refs, trim unused models.

`;

const ENUMS_HEADER = `// AUTO-GENERATED by scripts/split-models.ts — full enum copy from monolith (shared across clients).
// Prisma has no include: merge this file's contents into schema.prisma or keep as a second .prisma in the same folder.

`;

function parseArgs(argv: string[]): { schemaPath: string } {
  let schemaPath = process.env.SPLIT_MODELS_SCHEMA?.trim() || DEFAULT_SCHEMA;
  for (let i = 2; i < argv.length; i++) {
    if (argv[i] === "--schema" && argv[i + 1]) {
      schemaPath = path.isAbsolute(argv[i + 1])
        ? argv[i + 1]
        : path.join(REPO_ROOT, argv[i + 1]);
      i++;
    }
  }
  return { schemaPath };
}

/** Top-level model | enum blocks with balanced braces (same idea as split-prisma-by-domain.mjs). */
function extractTopLevelBlocks(text: string): Array<{
  kind: "model" | "enum";
  name: string;
  text: string;
  line: number;
}> {
  const lines = text.split("\n");
  const blocks: Array<{
    kind: "model" | "enum";
    name: string;
    text: string;
    line: number;
  }> = [];
  let i = 0;
  while (i < lines.length) {
    const m = lines[i].match(/^(model|enum)\s+(\w+)\s*\{\s*$/);
    if (m) {
      const kind = m[1] as "model" | "enum";
      const name = m[2];
      let depth = 0;
      let j = i;
      for (; j < lines.length; j++) {
        for (const ch of lines[j]) {
          if (ch === "{") depth++;
          if (ch === "}") depth--;
        }
        if (j > i && depth === 0) {
          const body = lines.slice(i, j + 1).join("\n");
          blocks.push({ kind, name, text: body, line: i + 1 });
          i = j + 1;
          break;
        }
      }
      if (j >= lines.length) {
        throw new Error(`Unclosed block at line ${i + 1} (${kind} ${name})`);
      }
      continue;
    }
    i++;
  }
  return blocks;
}

const CORE_NAMES = new Set(["User", "Account", "Session"]);

function bucketForModel(name: string): Bucket {
  if (CORE_NAMES.has(name)) return "core";
  if (/Listing|Property|Media/.test(name)) return "listings";
  if (/Booking|Price|Availability/.test(name)) return "bnhub";
  return "compliance";
}

function ensureDir(dir: string) {
  fs.mkdirSync(dir, { recursive: true });
}

function main() {
  const { schemaPath } = parseArgs(process.argv);

  if (!fs.existsSync(schemaPath)) {
    console.error(`Missing schema: ${schemaPath}`);
    process.exit(1);
  }

  const raw = fs.readFileSync(schemaPath, "utf8");
  const blocks = extractTopLevelBlocks(raw);
  const enums = blocks.filter((b) => b.kind === "enum");
  const models = blocks.filter((b) => b.kind === "model");

  const buckets: Record<Bucket, string[]> = {
    core: [],
    listings: [],
    bnhub: [],
    compliance: [],
  };

  for (const b of models) {
    buckets[bucketForModel(b.name)].push(b.text);
  }

  const enumsBody = ENUMS_HEADER + enums.map((b) => b.text).join("\n\n") + "\n";
  const artifactDir = path.join(__dirname, "split-models-artifacts");
  ensureDir(artifactDir);

  const summary = {
    schema: path.relative(REPO_ROOT, schemaPath),
    generatedAt: new Date().toISOString(),
    enumCount: enums.length,
    modelCount: models.length,
    buckets: {} as Record<Bucket, number>,
  };

  for (const key of BUCKETS) {
    const prismaDir = path.join(REPO_ROOT, `packages/db-${key}`, "prisma");
    ensureDir(prismaDir);
    const modelsPath = path.join(prismaDir, "models.prisma");
    const enumsPath = path.join(prismaDir, "enums.prisma");
    fs.writeFileSync(
      modelsPath,
      MODELS_HEADER + buckets[key].join("\n\n") + (buckets[key].length ? "\n" : ""),
      "utf8"
    );
    fs.writeFileSync(enumsPath, enumsBody, "utf8");
    summary.buckets[key] = buckets[key].length;
  }

  fs.writeFileSync(
    path.join(artifactDir, "last-run-summary.json"),
    JSON.stringify(summary, null, 2),
    "utf8"
  );

  console.log("Split complete.");
  console.log(JSON.stringify(summary, null, 2));
}

main();
