import type { AMLCheck } from "@/lib/compliance/oaciq/aml/types";

export const OACIQ_AML_RULES: readonly AMLCheck[] = [
  {
    id: "no_illegal_activity",
    trigger: "deal_created",
    condition: "transaction suspected illegal or harmful",
    violation: "broker involved in illegal or harmful activity",
    required_action: "stop transaction + escalate",
    severity: "critical",
    risk_score: 100,
    source: "OACIQ_AML",
  },
  {
    id: "identity_verification_required",
    trigger: "client_onboarding",
    condition: "identity not verified",
    violation: "missing identity verification",
    required_action: "verify identity before proceeding",
    severity: "critical",
    risk_score: 95,
    source: "OACIQ_AML",
  },
  {
    id: "legal_capacity_verification",
    trigger: "contract_sign",
    condition: "client legal capacity not confirmed",
    violation: "client may not legally transact",
    required_action: "validate legal capacity",
    severity: "critical",
    risk_score: 90,
    source: "OACIQ_AML",
  },
  {
    id: "trust_account_misuse",
    trigger: "funds_received",
    condition: "funds unrelated to brokerage mandate",
    violation: "illegal use of trust account",
    prohibited_action: "holding unrelated funds",
    severity: "critical",
    risk_score: 100,
    source: "OACIQ_AML",
  },
  {
    id: "suspicious_transaction",
    trigger: "deal_analysis",
    condition: "suspicious pattern detected",
    violation: "failure to report suspicious transaction",
    required_action: "flag + prepare FINTRAC report",
    severity: "critical",
    risk_score: 100,
    source: "OACIQ_AML",
  },
  {
    id: "record_keeping_required",
    trigger: "transaction_completed",
    condition: "missing records",
    violation: "non-compliance with record keeping",
    required_action: "store all documents (30 days accessible)",
    severity: "high",
    risk_score: 85,
    source: "OACIQ_AML",
  },
  {
    id: "reporting_entity_obligation",
    trigger: "broker_activity",
    condition: "broker fails reporting obligations",
    violation: "non-compliance with PCMLTFA",
    required_action: "submit required reports",
    severity: "critical",
    risk_score: 100,
    source: "OACIQ_AML",
  },
  {
    id: "value_mismatch",
    trigger: "deal_analysis",
    condition: "price differs from declared value",
    violation: "possible hidden payment",
    severity: "high",
    risk_score: 85,
    source: "OACIQ_AML",
  },
  {
    id: "nominee_buyer",
    trigger: "client_structure_analysis",
    condition: "buyer different from real beneficiary",
    violation: "hidden ownership",
    severity: "critical",
    risk_score: 95,
    source: "OACIQ_AML",
  },
  {
    id: "structured_transactions",
    trigger: "financial_analysis",
    condition: "multiple small deposits under threshold",
    violation: "avoid reporting threshold",
    severity: "critical",
    risk_score: 95,
    source: "OACIQ_AML",
  },
  {
    id: "abnormal_speed",
    trigger: "deal_timeline",
    condition: "transaction too fast without justification",
    violation: "potential laundering",
    severity: "medium",
    risk_score: 70,
    source: "OACIQ_AML",
  },
  {
    id: "over_financing",
    trigger: "mortgage_analysis",
    condition: "loan exceeds property value",
    violation: "suspicious financing",
    severity: "high",
    risk_score: 85,
    source: "OACIQ_AML",
  },
] as const;

/** Default scan — full catalog (KYC + trust + fraud indicators). */
export const DEFAULT_AML_DEAL_SCAN_RULE_IDS: readonly string[] = OACIQ_AML_RULES.map((r) => r.id);
