import type { LegalTemplateDefinition } from "./types";

export const bookingAgreementTemplate: LegalTemplateDefinition = {
  id: "booking_agreement",
  title: "Short-term booking agreement (draft)",
  suggestedKeys: [
    "HOST_LEGAL_NAME",
    "GUEST_LEGAL_NAME",
    "PROPERTY_ADDRESS",
    "PROPERTY_CITY",
    "EFFECTIVE_DATE",
    "CHECK_IN_DATE",
    "CHECK_OUT_DATE",
    "TOTAL_PRICE",
    "CURRENCY",
    "DEPOSIT_AMOUNT",
    "GOVERNING_LAW_NOTE",
  ],
  body: [
    "## Parties",
    "",
    "- **Host:** {{HOST_LEGAL_NAME}}",
    "- **Guest:** {{GUEST_LEGAL_NAME}}",
    "",
    "## Property",
    "",
    "- **Address:** {{PROPERTY_ADDRESS}}",
    "- **City / region:** {{PROPERTY_CITY}}",
    "",
    "## Stay dates",
    "",
    "- **Check-in:** {{CHECK_IN_DATE}}",
    "- **Check-out:** {{CHECK_OUT_DATE}}",
    "- **Agreement date:** {{EFFECTIVE_DATE}}",
    "",
    "## Fees (to be confirmed)",
    "",
    "- **Total consideration:** {{TOTAL_PRICE}} {{CURRENCY}}",
    "- **Deposit (if any):** {{DEPOSIT_AMOUNT}} {{CURRENCY}}",
    "",
    "## Incorporated terms",
    "",
    "The parties may attach house rules, platform booking terms, and any addenda. Blank fields must be completed before reliance on this draft.",
    "",
    "## Governing law (parties to complete)",
    "",
    "{{GOVERNING_LAW_NOTE}}",
    "",
    "## Signatures",
    "",
    "Host: _________________________  Date: __________",
    "",
    "Guest: ________________________  Date: __________",
    "",
  ].join("\n"),
};
