import type { LegalTemplateDefinition } from "./types";

export const brokerAgreementTemplate: LegalTemplateDefinition = {
  id: "broker_agreement",
  title: "Broker / platform cooperation agreement (draft)",
  suggestedKeys: [
    "BROKER_LEGAL_NAME",
    "BROKER_LICENSE_INFO",
    "PLATFORM_ENTITY_NAME",
    "SCOPE_SUMMARY",
    "COMPENSATION_SUMMARY",
    "EFFECTIVE_DATE",
    "TERM_END_DATE",
    "GOVERNING_LAW_NOTE",
  ],
  body: [
    "## Parties",
    "",
    "- **Broker / brokerage:** {{BROKER_LEGAL_NAME}}",
    "- **Licensing or registration (if applicable):** {{BROKER_LICENSE_INFO}}",
    "- **Platform entity (fill in):** {{PLATFORM_ENTITY_NAME}}",
    "",
    "## Purpose",
    "",
    "{{SCOPE_SUMMARY}}",
    "",
    "## Compensation (outline only)",
    "",
    "{{COMPENSATION_SUMMARY}}",
    "",
    "## Term",
    "",
    "- **Starts:** {{EFFECTIVE_DATE}}",
    "- **Ends / renewal (if stated):** {{TERM_END_DATE}}",
    "",
    "## Compliance",
    "",
    "Each party remains responsible for its own regulatory obligations. This draft does not determine licensing outcomes or commission entitlements.",
    "",
    "## Governing law (parties to complete)",
    "",
    "{{GOVERNING_LAW_NOTE}}",
    "",
    "## Signatures",
    "",
    "Broker: _________________________  Date: __________",
    "",
    "Platform representative: __________  Date: __________",
    "",
  ].join("\n"),
};
