import type { LegalTemplateDefinition } from "./types";

export const rentalAgreementTemplate: LegalTemplateDefinition = {
  id: "rental_agreement",
  title: "Residential rental agreement (draft)",
  suggestedKeys: [
    "LANDLORD_LEGAL_NAME",
    "TENANT_LEGAL_NAME",
    "PROPERTY_ADDRESS",
    "PROPERTY_CITY",
    "LEASE_START_DATE",
    "LEASE_END_DATE",
    "RENT_AMOUNT",
    "CURRENCY",
    "PAYMENT_DUE_DAY",
    "SECURITY_DEPOSIT",
    "GOVERNING_LAW_NOTE",
  ],
  body: [
    "## Parties",
    "",
    "- **Landlord:** {{LANDLORD_LEGAL_NAME}}",
    "- **Tenant:** {{TENANT_LEGAL_NAME}}",
    "",
    "## Premises",
    "",
    "- **Address:** {{PROPERTY_ADDRESS}}",
    "- **City / region:** {{PROPERTY_CITY}}",
    "",
    "## Term",
    "",
    "- **Start:** {{LEASE_START_DATE}}",
    "- **End:** {{LEASE_END_DATE}}",
    "",
    "## Rent and deposit (to be confirmed)",
    "",
    "- **Rent:** {{RENT_AMOUNT}} {{CURRENCY}}",
    "- **Due:** {{PAYMENT_DUE_DAY}}",
    "- **Security deposit (if any):** {{SECURITY_DEPOSIT}} {{CURRENCY}}",
    "",
    "## General",
    "",
    "This draft does not include mandatory statutory disclosures, local forms, or rent-control rules. Parties must replace bracketed items and add required schedules for their situation.",
    "",
    "## Governing law (parties to complete)",
    "",
    "{{GOVERNING_LAW_NOTE}}",
    "",
    "## Signatures",
    "",
    "Landlord: ______________________  Date: __________",
    "",
    "Tenant: _________________________  Date: __________",
    "",
  ].join("\n"),
};
