/**
 * Compliance Engine — constants.
 */

export const COMPLIANCE_CODES = {
  BROKER_REVIEW_REQUIRED: "BROKER_REVIEW_REQUIRED",
  SELLER_DECLARATION_MISSING: "SELLER_DECLARATION_MISSING",
  IDENTITY_NOT_VERIFIED: "IDENTITY_NOT_VERIFIED",
  LISTING_INCOMPLETE: "LISTING_INCOMPLETE",
  OACIQ_DISCLOSURE_MISSING: "OACIQ_DISCLOSURE_MISSING",
  HOST_TERMS_NOT_ACCEPTED: "HOST_TERMS_NOT_ACCEPTED",
  PAYMENT_METHOD_MISSING: "PAYMENT_METHOD_MISSING",
  UNKNOWN_REGULATED_ACTION: "UNKNOWN_REGULATED_ACTION",
} as const;

export type ComplianceCode = (typeof COMPLIANCE_CODES)[keyof typeof COMPLIANCE_CODES];
