import type { LecipmListingCentrisPublicationState } from "@prisma/client";
import { canAccessCrmListingCompliance } from "@/lib/compliance/crm-listing-access";
import { prisma } from "@/lib/db";
import { logListingTagged } from "@/lib/server/launch-logger";
import { getBrokerCentrisListingEligibility } from "@/lib/centris/centris-listing-eligibility.service";

/** Legal / product disclaimer — LECIPM never submits to Centris on the broker's behalf without explicit future integration. */
export const CENTRIS_MANUAL_EXPORT_DISCLAIMER =
  "This payload is generated by LECIPM for the broker to upload manually to the Centris portal (or authorized tools). LECIPM does not impersonate Centris and does not auto-publish listings to Centris unless a separate authorized integration is enabled.";

export type CentrisListingExportPayload = {
  schemaVersion: 1;
  generatedAt: string;
  disclaimer: string;
  listing: {
    id: string;
    listingCode: string;
    title: string;
    titleFr: string | null;
    price: number;
    listingType: string;
    isCoOwnership: boolean;
    crmMarketplaceLive: boolean;
    centrisPublicationState: LecipmListingCentrisPublicationState;
  };
  broker: {
    userId: string;
    name: string | null;
    email: string | null;
    licenceNumber: string | null;
    licenceStatus: string | null;
    centrisMemberId: string | null;
    hasCentrisAccess: boolean;
  };
  media: Array<{
    id: string;
    fileName: string;
    mimeType: string;
    storageKey: string;
  }>;
};

/**
 * Builds a broker-owned export package for manual Centris upload. Updates listing state to READY_FOR_CENTRIS.
 * Requires broker licence + hasCentrisAccess (same as publish eligibility when enforcement is on).
 */
export async function prepareCentrisPayload(params: {
  listingId: string;
  brokerUserId: string;
}): Promise<CentrisListingExportPayload> {
  const access = await canAccessCrmListingCompliance(params.brokerUserId, params.listingId);
  if (!access) {
    throw new Error("LISTING_NOT_FOUND_OR_FORBIDDEN");
  }

  const listing = await prisma.listing.findUnique({
    where: { id: params.listingId },
    select: {
      id: true,
      listingCode: true,
      title: true,
      titleFr: true,
      price: true,
      listingType: true,
      isCoOwnership: true,
      crmMarketplaceLive: true,
      centrisPublicationState: true,
      ownerId: true,
    },
  });
  if (!listing) {
    throw new Error("LISTING_NOT_FOUND_OR_FORBIDDEN");
  }

  const brokerForEligibility = listing.ownerId ?? params.brokerUserId;
  const eligibility = await getBrokerCentrisListingEligibility(brokerForEligibility);
  if (!eligibility.isLicensedBroker || !eligibility.hasCentrisAccess) {
    throw new Error("CENTRIS_EXPORT_NOT_ELIGIBLE");
  }

  const [user, files] = await Promise.all([
    prisma.user.findUnique({
      where: { id: brokerForEligibility },
      select: {
        id: true,
        name: true,
        email: true,
        lecipmBrokerLicenceProfile: {
          select: {
            licenceNumber: true,
            licenceStatus: true,
            centrisMemberId: true,
            hasCentrisAccess: true,
          },
        },
      },
    }),
    prisma.documentFile.findMany({
      where: {
        listingId: params.listingId,
        mimeType: { startsWith: "image/" },
        status: "AVAILABLE",
      },
      select: { id: true, fileName: true, mimeType: true, storageKey: true },
      orderBy: { createdAt: "asc" },
      take: 40,
    }),
  ]);

  const prof = user?.lecipmBrokerLicenceProfile;

  await prisma.listing.update({
    where: { id: params.listingId },
    data: {
      centrisPublicationState: "READY_FOR_CENTRIS",
    },
  });

  logListingTagged.info("prepared_for_centris", {
    listingId: params.listingId,
    brokerId: brokerForEligibility,
    actorId: params.brokerUserId,
  });

  return {
    schemaVersion: 1,
    generatedAt: new Date().toISOString(),
    disclaimer: CENTRIS_MANUAL_EXPORT_DISCLAIMER,
    listing: {
      id: listing.id,
      listingCode: listing.listingCode,
      title: listing.title,
      titleFr: listing.titleFr,
      price: listing.price,
      listingType: listing.listingType,
      isCoOwnership: listing.isCoOwnership,
      crmMarketplaceLive: listing.crmMarketplaceLive,
      centrisPublicationState: "READY_FOR_CENTRIS",
    },
    broker: {
      userId: brokerForEligibility,
      name: user?.name ?? null,
      email: user?.email ?? null,
      licenceNumber: prof?.licenceNumber ?? null,
      licenceStatus: prof?.licenceStatus ?? null,
      centrisMemberId: prof?.centrisMemberId ?? eligibility.centrisMemberId,
      hasCentrisAccess: prof?.hasCentrisAccess ?? eligibility.hasCentrisAccess,
    },
    media: files.map((f) => ({
      id: f.id,
      fileName: f.fileName,
      mimeType: f.mimeType,
      storageKey: f.storageKey,
    })),
  };
}
