/**
 * Preview-only policy evaluation — delegates to batch preview policy engine (read-only).
 */

import type { AutonomyMode, ObservationSnapshot, Opportunity, PolicyDecision } from "../types/domain.types";
import { evaluateListingPreviewPolicy } from "./preview-policy.service";

/**
 * Evaluates preview policies for each proposed action generated by the preview pipeline.
 */
export async function evaluatePreviewPoliciesForListing(params: {
  observation: ObservationSnapshot;
  opportunities: Opportunity[];
  autonomyMode: AutonomyMode;
}): Promise<PolicyDecision[]> {
  const proposedActions = params.opportunities.flatMap((o) => o.proposedActions);
  return evaluateListingPreviewPolicy({
    listingId: params.observation.target.id ?? "",
    observation: params.observation,
    opportunities: params.opportunities,
    proposedActions,
    autonomyMode: params.autonomyMode,
  });
}
