import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import type { DigitalSignature } from "@prisma/client";

function stripHtml(html: string): string {
  return html
    .replace(/<script[\s\S]*?<\/script>/gi, " ")
    .replace(/<style[\s\S]*?<\/style>/gi, " ")
    .replace(/<[^>]+>/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function wrapLines(text: string, maxChars: number): string[] {
  const words = text.split(/\s+/).filter(Boolean);
  const lines: string[] = [];
  let cur = "";
  for (const w of words) {
    const next = cur ? `${cur} ${w}` : w;
    if (next.length > maxChars) {
      if (cur) lines.push(cur);
      cur = w.length > maxChars ? w.slice(0, maxChars) : w;
    } else {
      cur = next;
    }
  }
  if (cur) lines.push(cur);
  return lines.length ? lines : [""];
}

/**
 * Builds a linearized PDF bundle: document body (plain text) + signature certificate page.
 * Tamper-evident linkage via embedded SHA-256 of canonical HTML at signing time per row.
 */
export async function buildLockedPdfBytes(input: {
  title: string;
  documentKind: string;
  bodyHtml: string;
  signatures: Pick<
    DigitalSignature,
    | "signerRole"
    | "signatureType"
    | "documentHash"
    | "recordHash"
    | "signedAt"
    | "templateVersionNumber"
    | "ipAddress"
    | "userAgent"
  >[];
  signerSummaries: { userId: string; name: string | null; email: string }[];
}): Promise<Uint8Array> {
  const pdf = await PDFDocument.create();
  pdf.setTitle(input.title);
  pdf.setSubject(`LECIPM signed bundle · ${input.documentKind}`);
  pdf.setProducer("LECIPM / digital-signature v1");
  pdf.setCreator("LECIPM platform");

  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const fontBold = await pdf.embedFont(StandardFonts.HelveticaBold);
  const margin = 48;
  const lineHeight = 14;
  const maxWidth = 520;
  const charsPerLine = 92;

  let page = pdf.addPage([612, 792]);
  let y = 750;
  page.drawText("Signed document (text extraction)", { x: margin, y, size: 12, font: fontBold, color: rgb(0.1, 0.1, 0.1) });
  y -= lineHeight * 2;

  const plain = stripHtml(input.bodyHtml);
  const lines = wrapLines(plain, charsPerLine);
  for (const line of lines) {
    if (y < 80) {
      page = pdf.addPage([612, 792]);
      y = 750;
      page.drawText("(continued)", { x: margin, y, size: 10, font, color: rgb(0.2, 0.2, 0.2) });
      y -= lineHeight * 2;
    }
    page.drawText(line.slice(0, 120), { x: margin, y, size: 9, font, color: rgb(0.15, 0.15, 0.15) });
    y -= lineHeight;
  }

  const cert = pdf.addPage([612, 792]);
  let cy = 750;
  cert.drawText("Signature certificate & integrity", {
    x: margin,
    y: cy,
    size: 14,
    font: fontBold,
    color: rgb(0.05, 0.05, 0.2),
  });
  cy -= lineHeight * 2;
  cert.drawText("This PDF was generated by LECIPM to bundle the document text and evidentiary signature records.", {
    x: margin,
    y: cy,
    size: 9,
    font,
    color: rgb(0.2, 0.2, 0.2),
  });
  cy -= lineHeight * 2;

  for (let i = 0; i < input.signatures.length; i++) {
    const s = input.signatures[i];
    const who = input.signerSummaries[i];
    const block = [
      `Signer ${i + 1}: ${who?.name ?? who?.userId ?? "unknown"} <${who?.email ?? ""}>`,
      `Role: ${s.signerRole} · Type: ${s.signatureType}`,
      `Document SHA-256: ${s.documentHash}`,
      `Record SHA-256: ${s.recordHash}`,
      `Template version #: ${s.templateVersionNumber}`,
      `Signed at (UTC): ${s.signedAt.toISOString()}`,
      `IP: ${s.ipAddress ?? "n/a"} · UA: ${(s.userAgent ?? "").slice(0, 80)}`,
    ];
    for (const ln of block) {
      cert.drawText(ln, { x: margin, y: cy, size: 8, font, color: rgb(0.15, 0.15, 0.15) });
      cy -= lineHeight;
    }
    cy -= lineHeight;
    if (cy < 100) break;
  }

  cert.drawText(
    "Modification of the underlying HTML after signing invalidates the document hash and requires a new signature.",
    { x: margin, y: 72, size: 8, font: fontBold, color: rgb(0.4, 0.2, 0.05) },
  );

  return pdf.save({ useObjectStreams: false });
}
