import type { FormDefinition } from "../../form-definition.types";

const partyBlock = (key: string, label: string, pathPrefix: string) => [
  {
    fieldKey: `${key}.fullName`,
    label: `${label} — name`,
    fieldType: "text" as const,
    required: false,
    sourcePaths: [`${pathPrefix}.fullName`],
    displayGroup: key,
    validationRuleRefs: [],
  },
  {
    fieldKey: `${key}.address`,
    label: `${label} — address`,
    fieldType: "textarea" as const,
    required: false,
    sourcePaths: [`${pathPrefix}.address`],
    displayGroup: key,
    validationRuleRefs: [],
  },
  {
    fieldKey: `${key}.roleIndicator`,
    label: `${label} — seller/buyer role`,
    fieldType: "text" as const,
    required: false,
    sourcePaths: [`${pathPrefix}.role`],
    displayGroup: key,
    validationRuleRefs: [],
  },
];

export const cpDefinition: FormDefinition = {
  formKey: "CP",
  officialCode: "CP",
  title: "Counter-proposal — specimen mapping",
  mandatoryOrRecommended: "recommended",
  versionLabel: "mapper-v1",
  principalOrRelated: "principal",
  baseWorkflow: "residential_sale_counter",
  sections: [
    {
      sectionKey: "cp.p1",
      sectionLabel: "CP.P1 Identification of parties",
      order: 1,
      description: "Counter-proposer and respondent blocks",
      fields: [
        ...partyBlock("cp.p1.counter1", "Counter-proposer 1", "deal.counterProposal.counterParties[0]"),
        ...partyBlock("cp.p1.counter2", "Counter-proposer 2", "deal.counterProposal.counterParties[1]"),
        ...partyBlock("cp.p1.respondent1", "Respondent 1", "deal.counterProposal.respondentParties[0]"),
        ...partyBlock("cp.p1.respondent2", "Respondent 2", "deal.counterProposal.respondentParties[1]"),
      ],
    },
    {
      sectionKey: "cp.p2",
      sectionLabel: "CP.P2 Amendments",
      order: 2,
      fields: [
        {
          fieldKey: "cp.p2.principalPpFormNumber",
          label: "Reference to principal PP form number",
          fieldType: "text",
          required: true,
          sourcePaths: ["deal.meta.principalFormNumber", "deal.documents.ppFormNumber"],
          displayGroup: "amendments",
          validationRuleRefs: ["cp.requires_pp_ref"],
        },
        {
          fieldKey: "cp.p2.immovableAddress",
          label: "Immovable address",
          fieldType: "textarea",
          required: true,
          sourcePaths: ["deal.immovable.addressLine", "deal.immovable.fullAddress"],
          displayGroup: "amendments",
          validationRuleRefs: [],
        },
        {
          fieldKey: "cp.p2.amendedPrice",
          label: "Amended price",
          fieldType: "currency",
          required: false,
          sourcePaths: ["deal.counterProposal.amendedPrice", "deal.price.purchasePrice"],
          displayGroup: "amendments",
          validationRuleRefs: [],
        },
        {
          fieldKey: "cp.p2.deedOfSaleDate",
          label: "Deed of sale date",
          fieldType: "date",
          required: false,
          sourcePaths: ["deal.dates.deedOfSale"],
          displayGroup: "amendments",
          validationRuleRefs: [],
        },
        {
          fieldKey: "cp.p2.occupancyDateTime",
          label: "Occupancy date/time",
          fieldType: "datetime",
          required: false,
          sourcePaths: ["deal.dates.occupancy"],
          displayGroup: "amendments",
          validationRuleRefs: [],
        },
        {
          fieldKey: "cp.p2.otherAmendments",
          label: "Other amendments (free text)",
          fieldType: "textarea",
          required: false,
          sourcePaths: ["deal.counterProposal.otherAmendments"],
          displayGroup: "amendments",
          validationRuleRefs: [],
        },
        {
          fieldKey: "cp.p2.annexReference",
          label: "Annex reference",
          fieldType: "textarea",
          required: false,
          sourcePaths: ["deal.documents.annexRefs"],
          displayGroup: "amendments",
          validationRuleRefs: [],
        },
        {
          fieldKey: "cp.p2.acceptanceConditions",
          label: "Acceptance conditions",
          fieldType: "textarea",
          required: false,
          sourcePaths: ["deal.conditions.acceptance"],
          displayGroup: "amendments",
          validationRuleRefs: [],
        },
        {
          fieldKey: "cp.p2.irrevocabilityDeadline",
          label: "Irrevocability deadline",
          fieldType: "datetime",
          required: false,
          sourcePaths: ["deal.dates.irrevocabilityDeadline"],
          displayGroup: "amendments",
          validationRuleRefs: [],
        },
        {
          fieldKey: "cp.p2.acceptOrRefuse",
          label: "Accept or refuse (workflow)",
          fieldType: "text",
          required: false,
          sourcePaths: ["deal.counterProposal.decision"],
          displayGroup: "signatures",
          validationRuleRefs: [],
        },
        {
          fieldKey: "cp.p2.signaturesPlaceholder",
          label: "Signatures (placeholder)",
          fieldType: "signature_placeholder",
          required: false,
          sourcePaths: [],
          displayGroup: "signatures",
          validationRuleRefs: [],
          notes: "Preview only",
        },
      ],
    },
  ],
  dependencies: [
    { ruleId: "cp.requires_pp", description: "Counter-proposal should reference principal PP", dependsOnFormKeys: ["PP"] },
  ],
  validationRules: [
    { ruleId: "cp.requires_pp_ref", description: "Principal PP form number should be present" },
  ],
  previewOrder: ["cp.p1", "cp.p2"],
};
